(function(){'use strict';
const Q=['data/questions-1.json','data/questions-2.json','data/questions-s1.json','data/mix.json','data/y01.json','data/y02c.json','data/q/052.json','data/q/053.json','data/q/054.json','data/q/055.json','data/q/056.json','data/q/160.json','data/q/178.json','data/q/d23.json','data/q/d24d25.json','data/q/164.json','data/q/070.json','data/q/068.json','data/q/177.json','data/q/201.json','data/q/202.json','data/q/203.json','data/q/204.json','data/q/e27-extra.json','data/q/e28-f29.json','data/q/f29-critical.json','data/q/082.json','data/q/086.json','data/q/087.json','data/q/205.json','data/q/f30-base.json','data/q/095.json','data/q/206.json','data/q/207.json','data/q/096.json','data/q/175.json','data/q/176.json'];
async function get(p){const r=await fetch(p,{cache:'no-store'});if(!r.ok)throw new Error(p);return r.json()}async function many(a){return(await Promise.all(a.map(get))).flat()}
let D={};
async function boot(){try{D={rsos:await get('data/rsos.json'),sources:await get('data/sources-v2.json'),terms:await many(['data/terms-1.json','data/terms-2.json']),questions:await many(Q)}}catch(e){document.body.innerHTML='<main class="fatal"><h2>Study data failed to load</h2><p>'+e.message+'</p></main>';return}nav();if(!window.ProfileStore.active())profile();else start()}
function start(){controls();spanish();home();rsos();calendar();progress();new window.EnglishController(document.querySelector('#english-root'),D.terms,refresh);new window.QuizController(document.querySelector('#quiz-root'),D.questions,D.rsos,D.sources,refresh)}
function refresh(){home();calendar();progress();controls();spanish()}
function profile(){const m=document.querySelector('#profile-modal');m.classList.add('open');m.innerHTML='<div class="modal-card"><h2>Create study user</h2><p>No email. Progress stays in this browser.</p><label class="field">Name<input id="pn" maxlength="32"></label><label class="field">Start date<input type="date" id="pd" value="'+window.ProfileStore.today()+'"></label><button class="button primary" id="pc">Start 180-day plan</button></div>';m.querySelector('#pc').onclick=()=>{try{window.ProfileStore.create(m.querySelector('#pn').value,m.querySelector('#pd').value);m.classList.remove('open');m.innerHTML='';start()}catch(e){alert(e.message)}}}
function controls(){const p=window.ProfileStore.active(),r=document.querySelector('#profile-controls');if(!p)return;r.innerHTML='<button class="profile-button" id="pm">👤 '+esc(p.name)+' · Day '+window.StudyCalendar.currentDay(p)+'</button><div class="profile-popover" id="pp">'+window.ProfileStore.list().map(x=>'<button data-p="'+x.id+'" class="profile-option">'+esc(x.name)+'</button>').join('')+'<button class="button secondary" id="pa">+ Add user</button></div>';const pop=r.querySelector('#pp');r.querySelector('#pm').onclick=()=>pop.classList.toggle('show');r.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{window.ProfileStore.setActive(b.dataset.p);location.reload()});r.querySelector('#pa').onclick=profile}
function nav(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab-button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id==='tab-'+b.dataset.tab))});document.querySelector('#spanish-toggle').onchange=e=>{window.ProgressStore.setSetting('showSpanish',e.target.checked);spanish()}}
function spanish(){const v=window.ProgressStore.getSetting('showSpanish',true);document.body.classList.toggle('hide-spanish',!v);const t=document.querySelector('#spanish-toggle');if(t)t.checked=v}
function home(){const p=window.ProfileStore.active(),s=window.ProgressStore.stats(),d=window.StudyCalendar.currentDay(p),x=window.StudyCalendar.planForDay(p,s,D.rsos,d),pct=s.quiz.answered?Math.round(s.quiz.correct/s.quiz.answered*100):0;document.querySelector('#home-root').innerHTML='<section class="hero"><div><p class="eyebrow">INDUSTRIAL ELECTRICIAN · CANADA · RED SEAL</p><h1>Prepare to <span>pass the Red Seal exam.</span></h1><p class="hero-copy">180 days of RSOS study, technical English and source-grounded exam practice.</p></div><aside class="hero-panel"><b>100 questions · 4 hours · 70% pass mark</b><p>Official MWA weighting: A9 / B23 / C20 / D21 / E10 / F17.</p></aside></section><div class="stat-grid"><div class="stat-card"><span>Day</span><strong>'+d+'/180</strong></div><div class="stat-card"><span>Practice</span><strong>'+pct+'%</strong></div><div class="stat-card"><span>Vocabulary</span><strong>'+s.mastered+'/'+D.terms.length+'</strong></div><div class="stat-card"><span>Streak</span><strong>'+s.streak+'</strong></div></div><article class="card today-plan"><div><span class="badge">TODAY</span><h3>'+esc(x.title)+'</h3><p>'+x.minutes+' min · '+x.vocab+' vocabulary · '+x.questions+' questions</p></div></article>'}
function calendar(){window.StudyCalendar.render(document.querySelector('#calendar-root'),D.rsos,refresh)}
function rsos(){const r=document.querySelector('#rsos-root');r.innerHTML='<div class="section-heading"><div><p class="eyebrow">OFFICIAL STUDY SPINE</p><h2>Industrial Electrician RSOS</h2></div><a class="button secondary" target="_blank" rel="noopener" href="'+D.sources.rsos.url+'">Official source ↗</a></div><div class="mwa-stack">'+D.rsos.mwas.map(m=>'<details class="card mwa-card"><summary><b>'+m.id+' · '+esc(m.title_en)+'</b><span>'+m.weight+'%</span></summary><div class="task-list">'+m.tasks.map(t=>'<article class="task-item"><div class="task-head"><b>'+t.id+'</b><h4>'+esc(t.title_en)+'</h4><span>'+t.exam_questions+' q</span></div><div class="subtask-list">'+t.subtasks.map(s=>'<span class="subtask-chip">'+esc(s.id)+' · '+esc(s.title_en)+'</span>').join('')+'</div></article>').join('')+'</div></details>').join('')+'</div>'}
function progress(){const s=window.ProgressStore.stats(),r=document.querySelector('#progress-root'),rows=Object.entries(s.quiz.byTask).map(([k,v])=>({k,n:v.answered,p:v.answered?Math.round(v.correct/v.answered*100):0})).sort((a,b)=>a.p-b.p);r.innerHTML='<div class="section-heading"><div><p class="eyebrow">PERSONAL PROGRESS</p><h2>'+esc(window.ProfileStore.active().name)+'</h2></div></div><div class="stat-grid"><div class="stat-card"><span>Answered</span><strong>'+s.quiz.answered+'</strong></div><div class="stat-card"><span>Mastered vocab</span><strong>'+s.mastered+'</strong></div><div class="stat-card"><span>Completed days</span><strong>'+s.calendar.completedDays.length+'</strong></div></div><article class="card chart-card">'+(rows.length?rows.map(x=>'<div class="bar-row"><b>'+x.k+'</b><span>'+x.p+'% · '+x.n+'</span></div>').join(''):'<p>No Task results yet.</p>')+'</article>'}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
document.addEventListener('DOMContentLoaded',boot);})();
