/* Practice UI for source-grounded Industrial Electrician study questions. */
(function(){'use strict';
class QuizController{
 constructor(root,questions,rsos,sources,onProgress){this.root=root;this.questions=questions;this.rsos=rsos;this.sources=sources;this.onProgress=onProgress;this.session=[];this.answers=[];this.index=0;this.mode='practice';this.seconds=0;this.timer=null;this.setup()}
 shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
 taskList(){return this.rsos.mwas.flatMap(m=>m.tasks.map(t=>({...t,mwa:m.id})))}
 daily(){const targets={'Knowledge and Recall':2,'Procedural and Application':4,'Critical Thinking':4},out=[];for(const [type,n] of Object.entries(targets))out.push(...this.shuffle(this.questions.filter(q=>q.answer_verified===true&&q.question_type===type)).slice(0,n));return this.shuffle(out)}
 filtered(){const m=this.root.querySelector('#q-mwa')?.value||'ALL',t=this.root.querySelector('#q-task')?.value||'ALL',k=this.root.querySelector('#q-type')?.value||'ALL';return this.questions.filter(q=>q.answer_verified===true&&(m==='ALL'||q.mwa===m)&&(t==='ALL'||q.task===t)&&(k==='ALL'||q.question_type===k))}
 start(mode){this.mode=mode;this.index=0;this.answers=[];clearInterval(this.timer);try{this.session=mode==='exam'?window.RedSealMockBuilder.build(this.questions,this.rsos):mode==='daily'?this.daily():this.shuffle(this.filtered()).slice(0,30)}catch(e){alert(e.message);return}if(!this.session.length){alert('No verified questions match the selection.');return}if(mode==='exam'){this.seconds=14400;document.body.classList.add('exam-english-only');this.timer=setInterval(()=>{this.seconds--;const x=this.root.querySelector('#quiz-timer');if(x)x.textContent=this.clock();if(this.seconds<=0)this.finish(true)},1000)}this.question()}
 clock(){const s=Math.max(0,this.seconds);return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
 setup(){document.body.classList.remove('exam-english-only');const tasks=this.taskList(),types=['Knowledge and Recall','Procedural and Application','Critical Thinking'];this.root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">INDUSTRIAL ELECTRICIAN EXAM PRACTICE</p><h2>Practice mapped to the RSOS</h2></div><span class="badge verified">${this.questions.filter(q=>q.answer_verified).length} reviewed study questions</span></div><div class="quiz-filter-grid"><label class="field">MWA<select id="q-mwa"><option value="ALL">All</option>${this.rsos.mwas.map(m=>`<option value="${m.id}">${m.id} · ${e(m.title_en)}</option>`).join('')}</select></label><label class="field">Task<select id="q-task"><option value="ALL">All</option>${tasks.map(t=>`<option value="${t.id}">${t.id} · ${e(t.title_en)}</option>`).join('')}</select></label><label class="field">Type<select id="q-type"><option value="ALL">All</option>${types.map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="quiz-launch-grid three"><button class="mode-card" id="daily"><strong>Daily 10</strong><span>10 mixed questions with feedback.</span></button><button class="mode-card" id="practice"><strong>Focused practice</strong><span>Up to 30 questions from your filters.</span></button><button class="mode-card exam-card" id="exam"><strong>Full mock</strong><span>100 questions · 4 hours · English only.</span></button></div><article class="card blueprint-card"><h3>Mock blueprint</h3><div class="weight-grid">${this.rsos.mwas.map(m=>`<div><b>${m.id}</b><span>${m.weight}%</span><small>${e(m.title_en)}</small></div>`).join('')}</div><p class="microcopy">Uses the official Task question counts. The simulated cognitive mix stays inside the published Red Seal ranges. These are original study questions, not official exam questions.</p></article>`;this.root.querySelector('#daily').onclick=()=>this.start('daily');this.root.querySelector('#practice').onclick=()=>this.start('practice');this.root.querySelector('#exam').onclick=()=>this.start('exam');this.root.querySelector('#q-mwa').onchange=ev=>{const m=ev.target.value,s=this.root.querySelector('#q-task');[...s.options].forEach(o=>{if(o.value!=='ALL')o.hidden=m!=='ALL'&&!o.value.startsWith(m+'-')});s.value='ALL'}}
 question(){if(this.index>=this.session.length){this.finish(false);return}const q=this.session[this.index],chosen=this.answers[this.index],exam=this.mode==='exam';this.root.innerHTML=`<div class="quiz-topbar"><button class="text-button" id="exit">← Exit</button><span>${this.index+1}/${this.session.length}</span>${exam?`<span class="timer" id="quiz-timer">${this.clock()}</span>`:'<span></span>'}</div><article class="card question-card"><div class="badge-row"><span class="badge">MWA ${e(q.mwa)}</span><span class="badge muted">${e(q.task)}</span><span class="badge muted">${e(q.subtask||'')}</span><span class="badge muted">${e(q.question_type)}</span></div><div class="question-title-row"><h3>${e(q.question_en)}</h3><button class="icon-button" id="hear">🔊</button></div><div class="options">${q.options.map((o,i)=>`<button class="option ${chosen===i?'selected':''}" data-i="${i}">${e(o)}</button>`).join('')}</div><div id="feedback"></div>${exam?`<div class="exam-nav"><button class="button secondary" id="prev" ${this.index===0?'disabled':''}>Previous</button><button class="button primary" id="next">${this.index===this.session.length-1?'Finish':'Next'}</button></div>`:''}</article>`;this.root.querySelector('#exit').onclick=()=>{clearInterval(this.timer);this.setup()};this.root.querySelector('#hear').onclick=()=>window.SpeechTools.speak(q.question_en);this.root.querySelectorAll('.option').forEach(b=>b.onclick=()=>this.choose(Number(b.dataset.i)));if(exam){this.root.querySelector('#prev').onclick=()=>{this.index--;this.question()};this.root.querySelector('#next').onclick=()=>{if(this.index===this.session.length-1)this.finish(false);else{this.index++;this.question()}}}}
 choose(i){const q=this.session[this.index];this.answers[this.index]=i;if(this.mode==='exam'){this.question();return}const ok=i===q.correct;window.ProgressStore.recordQuizAnswer(q,ok,{selectedIndex:i,mode:this.mode});this.onProgress?.();this.root.querySelectorAll('.option').forEach(b=>{b.disabled=true;const n=Number(b.dataset.i);if(n===q.correct)b.classList.add('correct');else if(n===i)b.classList.add('incorrect')});const src=this.sources[q.source_id]||{};this.root.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><h4>${ok?'Correct':'Review this concept'}</h4><p>${e(q.explanation_en)}</p><div class="lang-es"><p>${e(q.explanation_es)}</p></div><div class="evidence-box"><b>Study source</b><span>${e(q.source_locator||'Official Red Seal material')}</span>${src.url?`<a href="${src.url}" target="_blank" rel="noopener">Open source ↗</a>`:''}</div><button class="button primary" id="continue">Next</button></div>`;this.root.querySelector('#continue').onclick=()=>{this.index++;this.question()}}
 finish(expired){clearInterval(this.timer);document.body.classList.remove('exam-english-only');let correct=0;this.session.forEach((q,i)=>{const ok=this.answers[i]===q.correct;if(ok)correct++;if(this.mode==='exam')window.ProgressStore.recordQuizAnswer(q,ok,{selectedIndex:this.answers[i]??null,mode:'exam'})});const total=this.session.length,pct=Math.round(correct/total*100),passed=pct>=70;if(this.mode==='exam')window.ProgressStore.recordExamAttempt({score:correct,total,pct,passed,timeExpired:expired});this.onProgress?.();this.root.innerHTML=`<article class="card results-card"><p class="eyebrow">${expired?'TIME EXPIRED':'SESSION COMPLETE'}</p><h2>${correct}/${total} · ${pct}%</h2>${this.mode==='exam'?`<div class="pass-banner ${passed?'pass':'fail'}">${passed?'PASS ≥70%':'BELOW 70%'}</div>`:''}<button class="button primary" id="return">Return</button></article>`;this.root.querySelector('#return').onclick=()=>this.setup()}
}
function e(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
window.QuizController=QuizController;})();
