/* Main application controller. */
(function(){
'use strict';
const app={data:null,english:null,quiz:null,tab:'home'};
async function load(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json()}
async function loadMany(paths){return (await Promise.all(paths.map(load))).flat()}
const DATA_PARTS={terms:["data/terms-1.json", "data/terms-2.json", "data/terms-3.json", "data/terms-4.json", "data/terms-5.json", "data/terms-6.json"],questions:["data/questions-1.json", "data/questions-2.json", "data/questions-3.json", "data/questions-4.json", "data/questions-5.json", "data/questions-6.json", "data/questions-7.json", "data/questions-8.json"],guides:["data/study_guides-1.json", "data/study_guides-2.json", "data/study_guides-3.json"]};
async function boot(){try{app.data={rsos:await load('data/rsos.json'),terms:await loadMany(DATA_PARTS.terms),questions:await loadMany(DATA_PARTS.questions),guides:await loadMany(DATA_PARTS.guides),sources:await load('data/sources.json')}}catch(e){document.body.innerHTML=`<main class="fatal"><h1>Unable to load study data</h1><p>${esc(e.message)}</p><p>Open the app through GitHub Pages or a local HTTP server.</p></main>`;return}bindNav();if(!window.ProfileStore.active())showOnboarding();else startProfile();registerSW()}
function startProfile(){renderProfileControls();applySpanish();renderHome();renderRsos();renderCalendar();renderProgress();app.english=new window.EnglishController(document.querySelector('#english-root'),app.data.terms,refresh);app.quiz=new window.QuizController(document.querySelector('#quiz-root'),app.data.questions,app.data.rsos,app.data.sources,refresh)}
function refresh(){renderHome();renderProgress();renderCalendar();renderProfileControls();applySpanish()}
function showOnboarding(){const modal=document.querySelector('#profile-modal');modal.classList.add('open');modal.innerHTML=`<div class="modal-card"><p class="eyebrow">LOCAL STUDY PROFILE</p><h2>Create your study user</h2><p>No email or personal account is required. Progress is stored only in this browser/device.</p><label class="field">Study name<input id="new-profile-name" maxlength="32" placeholder="e.g. Hector"></label><label class="field">Study start date<input type="date" id="new-profile-date" value="${window.ProfileStore.today()}"></label><button class="button primary" id="create-profile">Start 180-day plan</button></div>`;modal.querySelector('#create-profile').onclick=()=>{try{window.ProfileStore.create(modal.querySelector('#new-profile-name').value,modal.querySelector('#new-profile-date').value);modal.classList.remove('open');modal.innerHTML='';startProfile()}catch(e){alert(e.message)}}}
function renderProfileControls(){const p=window.ProfileStore.active(),list=window.ProfileStore.list(),root=document.querySelector('#profile-controls');if(!p)return;root.innerHTML=`<button class="profile-button" id="profile-menu">👤 ${esc(p.name)} <small>Day ${window.StudyCalendar.currentDay(p)}/180</small></button><div class="profile-popover" id="profile-popover"><strong>Study profiles</strong>${list.map(x=>`<button data-profile="${x.id}" class="profile-option ${x.id===p.id?'active':''}">${esc(x.name)}<small>${x.startDate}</small></button>`).join('')}<button class="button secondary" id="add-profile">+ Add user</button></div>`;const pop=root.querySelector('#profile-popover');root.querySelector('#profile-menu').onclick=()=>pop.classList.toggle('show');root.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{window.ProfileStore.setActive(b.dataset.profile);location.reload()});root.querySelector('#add-profile').onclick=()=>showOnboarding()}
function bindNav(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>activate(b.dataset.tab));document.querySelector('#spanish-toggle').onchange=e=>{window.ProgressStore.setSetting('showSpanish',e.target.checked);applySpanish()}}
function activate(tab){app.tab=tab;document.querySelectorAll('.tab-button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${tab}`));window.scrollTo({top:0,behavior:'smooth'})}
function applySpanish(){const show=window.ProgressStore.getSetting('showSpanish',true);document.body.classList.toggle('hide-spanish',!show);const t=document.querySelector('#spanish-toggle');if(t)t.checked=show}
function renderHome(){const p=window.ProfileStore.active();if(!p)return;const s=window.ProgressStore.stats(),day=window.StudyCalendar.currentDay(p),plan=window.StudyCalendar.planForDay(p,s,app.data.rsos,day),pct=s.quiz.answered?Math.round(s.quiz.correct/s.quiz.answered*100):0,last=s.quiz.examAttempts.at(-1);document.querySelector('#home-root').innerHTML=`<section class="hero"><div><p class="eyebrow">INDUSTRIAL ELECTRICIAN · CANADA · RED SEAL</p><h1>Study to <span>pass the Red Seal exam.</span></h1><p class="hero-copy">A 180-day plan built around the official Industrial Electrician RSOS, official Task weightings, technical English, source-grounded practice and 100-question English-only mock exams.</p><div class="hero-actions"><button class="button primary" data-go="calendar">Today’s study plan</button><button class="button secondary" data-go="english">Technical English</button><button class="button secondary" data-go="quiz">Practice questions</button></div></div><aside class="hero-panel"><p class="eyebrow">OFFICIAL EXAM TARGET</p><div class="exam-facts"><div><b>100</b><span>questions</span></div><div><b>4 h</b><span>writing time</span></div><div><b>70%</b><span>pass mark</span></div></div><p>Question types: Knowledge/Recall 10–20%, Procedural/Application 35–45%, Critical Thinking 40–50%.</p></aside></section>
 <div class="stat-grid"><div class="stat-card"><span>Day</span><strong>${day}<small>/180</small></strong></div><div class="stat-card"><span>Practice accuracy</span><strong>${pct}<small>%</small></strong></div><div class="stat-card"><span>Vocabulary mastered</span><strong>${s.mastered}<small>/${app.data.terms.length}</small></strong></div><div class="stat-card"><span>Study streak</span><strong>${s.streak}<small>days</small></strong></div></div>
 <article class="card today-plan home-today"><div><span class="badge">TODAY · ${esc(plan.phase)}</span><h3>${esc(plan.title)}</h3><p>${esc(plan.desc)}</p><div class="plan-metrics"><span>⏱ ${plan.minutes} min</span><span>🔤 ${plan.vocab} vocab</span><span>📝 ${plan.questions} questions</span></div></div><button class="button primary" data-go="calendar">Open day</button></article>
 <div class="dashboard-grid"><article class="card dashboard-card"><h3>180-day readiness goal</h3><p><b>Internal target: ≥80% on 3 consecutive full mocks</b></p><p>The official pass mark is 70%; the higher study target creates margin before the real exam.</p></article><article class="card dashboard-card"><h3>Official scope</h3><p><b>6 MWA · 31 Tasks · 112 Sub-tasks</b></p><p>The full curriculum navigator mirrors the official Industrial Electrician task matrix.</p><button class="text-button" data-go="rsos">Open RSOS curriculum →</button></article><article class="card dashboard-card"><h3>Last full mock</h3>${last?`<p><b>${last.pct}%</b> · ${last.passed?'PASS':'below target'}</p><p>${new Date(last.at).toLocaleDateString()}</p>`:'<p>No 100-question mock completed yet.</p>'}<button class="text-button" data-go="quiz">Open exam mode →</button></article><article class="card dashboard-card"><h3>Important</h3><p>This app prepares you for the exam; it does not grant Red Seal certification. Eligibility and certification are administered by Canadian provincial/territorial apprenticeship authorities.</p></article></div>`;document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>activate(b.dataset.go))}
function renderCalendar(){window.StudyCalendar.render(document.querySelector('#calendar-root'),app.data.rsos,refresh)}
function renderRsos(){
 const root=document.querySelector('#rsos-root'),guideMap=new Map(app.data.guides.map(g=>[g.task,g]));
 root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">OFFICIAL CURRICULUM + STUDY GUIDE</p><h2>Industrial Electrician RSOS</h2></div><a class="button secondary" href="${app.data.sources['rsos-pdf']?.url||app.data.sources.rsos.url}" target="_blank" rel="noopener">Official RSOS ↗</a></div><p class="section-intro">This is the study spine: 6 Major Work Activities, 31 Tasks and 112 Sub-tasks. The exam blueprint is tracked at Task level; study coverage is tracked down to Sub-task.</p><div class="mwa-stack">${app.data.rsos.mwas.map(m=>`<details class="card mwa-card" ${m.id==='D'||m.id==='F'?'open':''}><summary><div><span class="mwa-letter">${m.id}</span><div><h3>${esc(m.title_en)}</h3><p>${m.weight}% · ${m.tasks.reduce((n,t)=>n+t.exam_questions,0)} exam questions</p></div></div></summary><div class="task-list">${m.tasks.map(t=>{const g=guideMap.get(t.id);return `<article class="task-item"><div class="task-head"><b>${t.id}</b><h4>${esc(t.title_en)}</h4><span>${t.exam_questions} q</span></div><div class="subtask-list">${t.subtasks.map(s=>`<span class="subtask-chip">${esc(s.id)} · ${esc(s.title_en)}</span>`).join('')}</div>${g?`<details class="task-guide"><summary>Study focus for ${t.id}</summary><div class="guide-body"><p><strong>What to master</strong></p><ul>${(g.focus_en||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="microcopy">Study the RSOS performance criteria, learning outcomes and range of variables. Where the RSOS refers to CEC/code requirements, verify the requirement in the current codebook rather than memorizing an unsupported value from this app.</p></div></details>`:''}</article>`}).join('')}</div></details>`).join('')}</div>`}
function renderProgress(){const root=document.querySelector('#progress-root'),s=window.ProgressStore.stats();const total=s.quiz.answered,pct=total?Math.round(s.quiz.correct/total*100):0;const taskRows=app.data.rsos.mwas.flatMap(m=>m.tasks.map(t=>{const v=s.quiz.byTask[t.id]||{answered:0,correct:0};return{...t,mwa:m.id,answered:v.answered,pct:v.answered?Math.round(v.correct/v.answered*100):0}})).filter(x=>x.answered).sort((a,b)=>a.pct-b.pct);root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">PERSONAL PROGRESS</p><h2>${esc(window.ProfileStore.active().name)}’s study record</h2></div><span class="badge">Local to this browser</span></div><div class="stat-grid"><div class="stat-card"><span>Questions answered</span><strong>${total}</strong></div><div class="stat-card"><span>Accuracy</span><strong>${pct}<small>%</small></strong></div><div class="stat-card"><span>Mastered vocabulary</span><strong>${s.mastered}</strong></div><div class="stat-card"><span>Completed study days</span><strong>${s.calendar.completedDays.length}<small>/180</small></strong></div></div><article class="card chart-card"><h3>Task performance</h3>${taskRows.length?taskRows.map(x=>`<div class="bar-row"><div class="bar-label"><b>${x.id}</b><span>${x.pct}% · ${x.answered} answers</span></div><div class="bar-track"><div class="bar-value" style="width:${x.pct}%"></div></div></div>`).join(''):'<div class="empty-state">Answer practice questions to build Task-level diagnostics.</div>'}</article>`}
function registerSW(){if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(console.warn)}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
document.addEventListener('DOMContentLoaded',boot);
})();
