/* Main application controller: profiles, guided daily workflow and adaptive resume. */
(function(){
'use strict';
const app={data:null,english:null,quiz:null,tab:'home',started:false};
async function load(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json()}
async function loadMany(paths){return (await Promise.all(paths.map(load))).flat()}
const DATA_PARTS={terms:["data/terms-1.json","data/terms-2.json","data/terms-3.json","data/terms-4.json","data/terms-5.json","data/terms-6.json"],questions:["data/questions-1.json","data/questions-2.json","data/questions-3.json","data/questions-4.json","data/questions-5.json","data/questions-6.json","data/questions-7.json","data/questions-8.json"],guides:["data/study_guides-1.json","data/study_guides-2.json","data/study_guides-3.json"]};
async function boot(){try{app.data={rsos:await load('data/rsos.json'),terms:await loadMany(DATA_PARTS.terms),questions:await loadMany(DATA_PARTS.questions),guides:await loadMany(DATA_PARTS.guides),sources:await load('data/sources.json')};window.__RSOS_DATA__=app.data.rsos}catch(e){document.body.innerHTML=`<main class="fatal"><h1>Unable to load study data</h1><p>${esc(e.message)}</p></main>`;return}bindNav();window.addEventListener('study:navigate',handleStudyNavigate);await removeLegacyRootServiceWorker();if(!window.ProfileStore.active())showProfileGate();else startProfile();registerSW()}
function startProfile(){app.started=true;renderProfileControls();applySpanish();renderHome();renderRsos();renderCalendar();renderProgress();app.english=new window.EnglishController(document.querySelector('#english-root'),app.data.terms,refresh);app.quiz=new window.QuizController(document.querySelector('#quiz-root'),app.data.questions,app.data.rsos,app.data.sources,refresh)}
function refresh(){if(!window.ProfileStore.active())return;renderHome();renderProgress();renderCalendar();renderProfileControls();applySpanish()}
function showProfileGate(force=false){const modal=document.querySelector('#profile-modal'),list=window.ProfileStore.list(),active=window.ProfileStore.active();modal.classList.add('open');modal.innerHTML=`<div class="modal-card profile-gate"><p class="eyebrow">LOCAL STUDY USERS</p><h2>${list.length?'Choose or create a study user':'Create your study user'}</h2><p>Each user has a separate 180-day calendar, vocabulary memory, question history, weak areas and mock results. No email is required.</p>${list.length?`<div class="profile-list">${list.map(p=>`<button class="profile-select ${p.id===active?.id?'active':''}" data-use="${p.id}"><strong>${esc(p.name)}</strong><span>${p.startDate} → ${p.targetDate}</span></button>`).join('')}</div>`:''}<hr><h3>New user</h3><label class="field">Study name<input id="new-profile-name" maxlength="32" placeholder="e.g. Hector"></label><label class="field">Study start date<input type="date" id="new-profile-date" value="${window.ProfileStore.today()}"></label><button class="button primary" id="create-profile">Create user and start 180-day plan</button>${force&&active?'<button class="button secondary" id="close-profile-gate">Cancel</button>':''}</div>`;
 modal.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{window.ProfileStore.setActive(b.dataset.use);location.reload()});modal.querySelector('#create-profile').onclick=()=>{try{window.ProfileStore.create(modal.querySelector('#new-profile-name').value,modal.querySelector('#new-profile-date').value);location.reload()}catch(e){alert(e.message)}};const close=modal.querySelector('#close-profile-gate');if(close)close.onclick=()=>modal.classList.remove('open')}
function renderProfileControls(){const p=window.ProfileStore.active(),root=document.querySelector('#profile-controls');if(!p)return;root.innerHTML=`<div class="active-user"><span>STUDY USER</span><strong>👤 ${esc(p.name)}</strong><small>Day ${window.StudyCalendar.currentDay(p)}/180</small></div><button class="button secondary compact" id="manage-users">Users</button>`;root.querySelector('#manage-users').onclick=()=>showProfileGate(true)}
function bindNav(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>activate(b.dataset.tab));document.querySelector('#spanish-toggle').onchange=e=>{window.ProgressStore.setSetting('showSpanish',e.target.checked);applySpanish()}}
function activate(tab,opts={}){if(!window.ProfileStore.active())return;app.tab=tab;document.querySelectorAll('.tab-button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${tab}`));window.ProgressStore.setResume(tab,opts.mode||null,opts.questionId||null);if(tab==='rsos'&&opts.task)renderRsos(opts.task);window.scrollTo({top:0,behavior:'smooth'})}
function handleStudyNavigate(e){const d=e.detail||{};activate(d.tab||'home',{mode:d.mode});if(d.tab==='english'&&app.english&&d.mode)app.english.open(d.mode);if(d.tab==='quiz'&&app.quiz&&d.mode)app.quiz.open(d.mode);if(d.tab==='rsos')renderRsos(d.task||todayPlan().task?.id||null)}
function applySpanish(){const show=window.ProgressStore.getSetting('showSpanish',true);document.body.classList.toggle('hide-spanish',!show);const t=document.querySelector('#spanish-toggle');if(t)t.checked=show}
function todayPlan(){const p=window.ProfileStore.active(),s=window.ProgressStore.load(),day=window.StudyCalendar.currentDay(p);return window.StudyCalendar.planForDay(p,s,app.data.rsos,day)}
function renderHome(){const p=window.ProfileStore.active();if(!p)return;const s=window.ProgressStore.stats(),day=window.StudyCalendar.currentDay(p),plan=todayPlan(),status=window.StudyCalendar.statusFor(day,plan),next=window.StudyCalendar.nextStep(plan,status),pct=s.quiz.answered?Math.round(s.quiz.correct/s.quiz.answered*100):0,last=s.quiz.examAttempts.at(-1),weak=s.weakTasks.slice(0,3);document.querySelector('#home-root').innerHTML=`<section class="hero"><div><p class="eyebrow">${esc(p.name.toUpperCase())} · INDUSTRIAL ELECTRICIAN · CANADA</p><h1>Pass the <span>Red Seal.</span></h1><p class="hero-copy">Your study path follows the Industrial Electrician RSOS, tracks what you actually answer, and adapts future remediation to weak Tasks, Sub-tasks and missed questions.</p><div class="hero-actions"><button class="button primary" id="continue-study">${esc(next.label)}</button><button class="button secondary" data-go="progress">See my progress</button><button class="button secondary" id="home-users">Switch/create user</button></div></div><aside class="hero-panel"><p class="eyebrow">TODAY · DAY ${day}/180</p><h3>${esc(plan.title)}</h3><p>${status.complete?'✓ Today is complete.':'Complete the required English, RSOS lesson and guided questions.'}</p><div class="daily-mini-progress"><span>${new Set(status.p.vocabReviewed||[]).size}/${status.r.vocab} vocab</span><span>${status.p.vocabTestPct??0}% English test</span><span>${status.p.quizAnswered}/${status.r.quiz} questions</span></div></aside></section>
 <div class="stat-grid"><div class="stat-card"><span>Day</span><strong>${day}<small>/180</small></strong></div><div class="stat-card"><span>Question accuracy</span><strong>${pct}<small>%</small></strong></div><div class="stat-card"><span>Vocabulary mastered</span><strong>${s.mastered}<small>/${app.data.terms.length}</small></strong></div><div class="stat-card"><span>Study streak</span><strong>${s.streak}<small>days</small></strong></div></div>
 <article class="card workflow-card"><div class="section-heading compact-heading"><div><p class="eyebrow">TODAY’S REQUIRED PATH</p><h3>${esc(plan.phase)}</h3></div><span class="day-status ${status.complete?'complete':'inprogress'}">${status.complete?'COMPLETE':'IN PROGRESS'}</span></div>${workflowHtml(plan,status)}<button class="button primary" id="continue-study-2">${esc(next.label)}</button></article>
 <div class="dashboard-grid"><article class="card dashboard-card"><h3>Measured weak areas</h3>${weak.length?weak.map(w=>`<p><b>${esc(w.task)}</b> · ${w.pct}% over ${w.answered} answers</p>`).join(''):'<p>Complete guided questions to build your diagnostic profile.</p>'}<button class="text-button" data-go="progress">Open diagnostics →</button></article><article class="card dashboard-card"><h3>Mock readiness</h3>${last?`<p><b>${last.pct}%</b> on last 100-question mock</p>`:'<p>No full mock completed yet.</p>'}<p>Study goal: ≥80% on three consecutive mocks; official pass mark remains 70%.</p></article><article class="card dashboard-card"><h3>Question bank</h3><p><b>${app.data.questions.filter(q=>q.depth!=='scope').length}</b> exam-style/application questions currently separated from optional RSOS-map drills.</p><button class="text-button" data-go="quiz">Practice →</button></article></div>`;
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>activate(b.dataset.go));const go=()=>window.dispatchEvent(new CustomEvent('study:navigate',{detail:{tab:next.tab,mode:next.mode,task:plan.task?.id||null}}));document.querySelector('#continue-study').onclick=go;document.querySelector('#continue-study-2').onclick=go;document.querySelector('#home-users').onclick=()=>showProfileGate(true)}
function workflowHtml(plan,s){if(s.r.mock)return`<div class="study-checklist"><div class="study-step ${s.steps.mock?'done':''}"><b>${s.steps.mock?'✓':'1'}</b><div><strong>100-question mock</strong><span>${s.p.mockCompleted?s.p.mockPct+'% completed':'4 hours · English only'}</span></div></div></div>`;return`<div class="study-checklist"><div class="study-step ${s.steps.vocab?'done':''}"><b>${s.steps.vocab?'✓':'1'}</b><div><strong>Technical English</strong><span>${s.v}/${s.r.vocab} reviews</span></div></div><div class="study-step ${s.steps.vocabTest?'done':''}"><b>${s.steps.vocabTest?'✓':'2'}</b><div><strong>English evaluation</strong><span>${s.p.vocabTestPct??0}% · target ≥80%</span></div></div>${s.r.lesson?`<div class="study-step ${s.steps.lesson?'done':''}"><b>${s.steps.lesson?'✓':'3'}</b><div><strong>RSOS lesson</strong><span>${esc(plan.task?.id||'Weekly review')}</span></div></div>`:''}<div class="study-step ${s.steps.quiz?'done':''}"><b>${s.steps.quiz?'✓':'4'}</b><div><strong>Guided questions</strong><span>${s.p.quizAnswered}/${s.r.quiz} answered</span></div></div></div>`}
function renderCalendar(){window.StudyCalendar.render(document.querySelector('#calendar-root'),app.data.rsos,refresh)}
function renderRsos(focusTask=null){const root=document.querySelector('#rsos-root'),guideMap=new Map(app.data.guides.map(g=>[g.task,g])),plan=todayPlan(),todayTask=plan.task?.id||null;root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">OFFICIAL RSOS STUDY SPINE</p><h2>Industrial Electrician curriculum</h2><p class="section-intro">Tasks and Sub-tasks organize what the Red Seal exam assesses. Use the guide to study the activity; optional map-drill questions are kept separate from exam-style practice.</p></div><a class="button secondary" href="${app.data.sources['rsos-pdf']?.url||app.data.sources.rsos.url}" target="_blank" rel="noopener">Official RSOS ↗</a></div><div class="mwa-stack">${app.data.rsos.mwas.map(m=>`<details class="card mwa-card" ${m.tasks.some(t=>t.id===(focusTask||todayTask))?'open':''}><summary><div><span class="mwa-letter">${m.id}</span><div><h3>${esc(m.title_en)}</h3><p>${m.weight}% · ${m.tasks.reduce((n,t)=>n+t.exam_questions,0)} exam questions</p></div></div></summary><div class="task-list">${m.tasks.map(t=>{const g=guideMap.get(t.id),isFocus=t.id===(focusTask||todayTask),done=window.ProgressStore.getDayProgress().lessonViewed&&window.ProgressStore.getDayProgress().lessonTask===t.id;return `<article class="task-item ${isFocus?'focus-task':''}" id="task-${t.id}"><div class="task-head"><b>${t.id}</b><h4>${esc(t.title_en)}</h4><span>${t.exam_questions} q</span></div><div class="subtask-list">${t.subtasks.map(s=>`<span class="subtask-chip">${esc(s.id)} · ${esc(s.title_en)}</span>`).join('')}</div>${g?`<div class="guide-body"><p><strong>Study focus</strong></p><ul>${(g.focus_en||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="lang-es"><strong>ES support:</strong> ${(g.focus_es||[]).map(esc).join(' · ')}</p><p class="microcopy">Use the official RSOS performance criteria and learning outcomes as the source of truth. When a requirement depends on the CEC or another standard, verify it in the current applicable codebook.</p></div>`:''}${t.id===todayTask?`<button class="button ${done?'success':'primary'} lesson-complete" data-lesson="${t.id}" ${done?'disabled':''}>${done?'✓ Today’s RSOS lesson completed':'Mark today’s RSOS lesson studied'}</button>`:''}</article>`}).join('')}</div></details>`).join('')}</div>`;root.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{window.ProgressStore.markLessonViewed(b.dataset.lesson);refresh();renderRsos(b.dataset.lesson);setTimeout(()=>document.querySelector(`#task-${CSS.escape(b.dataset.lesson)}`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)});if(focusTask)setTimeout(()=>document.querySelector(`#task-${CSS.escape(focusTask)}`)?.scrollIntoView({behavior:'smooth',block:'center'}),80)}
function renderProgress(){const root=document.querySelector('#progress-root'),s=window.ProgressStore.stats(),total=s.quiz.answered,pct=total?Math.round(s.quiz.correct/total*100):0,taskRows=app.data.rsos.mwas.flatMap(m=>m.tasks.map(t=>{const v=s.quiz.byTask[t.id]||{answered:0,correct:0};return{...t,mwa:m.id,answered:v.answered,pct:v.answered?Math.round(v.correct/v.answered*100):0}})).filter(x=>x.answered).sort((a,b)=>a.pct-b.pct),subRows=s.weakSubtasks||[];root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">PERSONAL LEARNING RECORD</p><h2>${esc(window.ProfileStore.active().name)}’s diagnostics</h2></div><span class="badge">Stored locally for this user</span></div><div class="stat-grid"><div class="stat-card"><span>Questions answered</span><strong>${total}</strong></div><div class="stat-card"><span>Accuracy</span><strong>${pct}<small>%</small></strong></div><div class="stat-card"><span>Vocabulary mastered</span><strong>${s.mastered}</strong></div><div class="stat-card"><span>Completed days</span><strong>${s.calendar.completedDays.length}<small>/180</small></strong></div></div><div class="progress-layout"><article class="card chart-card"><h3>Task performance</h3>${taskRows.length?taskRows.map(x=>`<div class="bar-row"><div class="bar-label"><b>${x.id}</b><span>${x.pct}% · ${x.answered} answers</span></div><div class="bar-track"><div class="bar-value" style="width:${x.pct}%"></div></div></div>`).join(''):'<div class="empty-state">Your Task profile will appear after guided practice.</div>'}</article><article class="card chart-card"><h3>Weak Sub-tasks</h3>${subRows.length?subRows.map(x=>`<p><b>${esc(x.subtask)}</b> · ${x.pct}% over ${x.answered} answers</p>`).join(''):'<div class="empty-state">No Sub-task weakness has enough evidence yet.</div>'}<h3>Remediation queue</h3><p>${window.ProgressStore.missedQuestionIds(50).length} missed questions currently waiting for spaced retry.</p></article></div>`}
async function removeLegacyRootServiceWorker(){if(!('serviceWorker'in navigator))return;try{const regs=await navigator.serviceWorker.getRegistrations(),here=new URL('.',location.href).pathname,parent=here.replace(/v2\/?$/,'');for(const r of regs){const p=new URL(r.scope).pathname;if(p===parent&&p!==here)await r.unregister()}}catch(e){console.warn('legacy SW cleanup',e)}}
function registerSW(){if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js',{scope:'./'}).catch(console.warn)}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
document.addEventListener('DOMContentLoaded',boot);
})();
