/* Adaptive 180-day Red Seal study calendar. Completion is earned by study activity, not a manual checkbox. */
(function(){
'use strict';
const DAY=86400000;
function daysBetween(a,b){return Math.floor((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/DAY)}
function flatten(rsos){return rsos.mwas.flatMap(m=>m.tasks.map(t=>({...t,mwa:m.id,mwaTitle:m.title_en})))}
function weightedTasks(rsos){return flatten(rsos).flatMap(t=>Array(Math.max(1,t.exam_questions)).fill(t))}
function planForDay(profile,progress,rsos,day){const all=flatten(rsos),weighted=weightedTasks(rsos),i=Math.max(1,Math.min(180,day));
  if(i<=126){if(i%7===0)return{day:i,phase:'Foundation review',kind:'weekly-review',title:'Weekly consolidation + mixed Red Seal practice',minutes:90,vocab:8,questions:20,desc:'Review the week, repeat missed concepts and complete a mixed English session.'};const t=weighted[(i*7+Math.floor(i/7))%weighted.length];return{day:i,phase:'RSOS foundation',kind:'core',title:`${t.id} · ${t.title_en}`,minutes:70,vocab:5,questions:10,task:t,desc:'Study the official Task/Sub-tasks, learn technical English tied to the Task, then answer application-focused questions.'}}
  if(i<=154){if(i%7===0)return{day:i,phase:'Integration & troubleshooting',kind:'mixed-test',title:'Timed mixed diagnostic set',minutes:120,vocab:8,questions:25,desc:'Work in English and use the result to update weak Tasks/Sub-tasks.'};const weak=window.ProgressStore.weakTasks(8);const wid=weak[(i-127)%Math.max(1,weak.length)]?.task;const t=all.find(x=>x.id===wid)||weighted[(i*11)%weighted.length];return{day:i,phase:'Integration & troubleshooting',kind:'integration',title:`Applied diagnosis · ${t.id}`,minutes:85,vocab:6,questions:15,task:t,desc:'Prioritize procedural and critical-thinking scenarios and repair weak concepts.'}}
  if([160,167,174,178,180].includes(i))return{day:i,phase:'Final exam readiness',kind:'full-mock',title:'100-question / 4-hour full mock',minutes:240,vocab:0,questions:100,desc:'English-only simulation using the official Task question counts. Review errors only after finishing.'};
  const weak=window.ProgressStore.weakTasks(10),wid=weak[(i-155)%Math.max(1,weak.length)]?.task,t=all.find(x=>x.id===wid)||weighted[(i*5)%weighted.length];return{day:i,phase:'Final exam readiness',kind:'remediation',title:`Weak-area remediation · ${t.id}`,minutes:90,vocab:6,questions:15,task:t,desc:'Repair the weakest measured area, repeat missed questions and reinforce technical English.'}
}
function requirementsForDay(plan){if(plan?.kind==='full-mock')return{vocab:0,vocabTest:false,lesson:false,quiz:0,mock:true};if(plan?.kind==='weekly-review')return{vocab:8,vocabTest:true,lesson:false,quiz:20,mock:false};if(plan?.kind==='mixed-test')return{vocab:8,vocabTest:true,lesson:false,quiz:25,mock:false};return{vocab:Math.min(6,plan?.vocab||5),vocabTest:true,lesson:true,quiz:plan?.questions||10,mock:false}}
function currentDay(profile){return Math.max(1,Math.min(180,daysBetween(profile.startDate,window.ProfileStore.today())+1))}
function dateFor(profile,day){return window.ProfileStore.addDays(profile.startDate,day-1)}
function statusFor(day,plan){const p=window.ProgressStore.getDayProgress(day),r=requirementsForDay(plan),v=new Set(p.vocabReviewed||[]).size;return{p,r,v,steps:{vocab:v>=r.vocab,vocabTest:!r.vocabTest||Number(p.vocabTestPct)>=80,lesson:!r.lesson||!!p.lessonViewed,quiz:Number(p.quizAnswered)>=r.quiz,mock:!r.mock||!!p.mockCompleted},complete:r.mock?!!p.mockCompleted:(v>=r.vocab&&(!r.vocabTest||Number(p.vocabTestPct)>=80)&&(!r.lesson||!!p.lessonViewed)&&Number(p.quizAnswered)>=r.quiz)}}
function nextStep(plan,s){if(s.r.mock&&!s.steps.mock)return{tab:'quiz',mode:'exam',label:'Start full mock'};if(!s.steps.vocab)return{tab:'english',mode:'cards',label:'Study technical English'};if(!s.steps.vocabTest)return{tab:'english',mode:'test',label:'Take vocabulary evaluation'};if(!s.steps.lesson)return{tab:'rsos',mode:'lesson',label:`Study ${plan.task?.id||'today’s Task'}`};if(!s.steps.quiz)return{tab:'quiz',mode:'guided',label:'Continue guided questions'};return{tab:'progress',mode:null,label:'Review today’s results'}}
function go(tab,mode,task){window.dispatchEvent(new CustomEvent('study:navigate',{detail:{tab,mode,task}}))}
function renderChecklist(plan,s){if(s.r.mock)return`<div class="study-checklist"><div class="study-step ${s.steps.mock?'done':''}"><b>${s.steps.mock?'✓':'1'}</b><div><strong>Full Red Seal mock</strong><span>${s.p.mockCompleted?`${s.p.mockPct}% completed`:'100 questions · 4 hours · English only'}</span></div></div></div>`;return`<div class="study-checklist">
 <div class="study-step ${s.steps.vocab?'done':''}"><b>${s.steps.vocab?'✓':'1'}</b><div><strong>Technical English</strong><span>${s.v}/${s.r.vocab} scheduled reviews completed</span></div></div>
 <div class="study-step ${s.steps.vocabTest?'done':''}"><b>${s.steps.vocabTest?'✓':'2'}</b><div><strong>Vocabulary evaluation</strong><span>${s.p.vocabTestPct==null?'Not attempted':`${s.p.vocabTestPct}%`} · target ≥80%</span></div></div>
 ${s.r.lesson?`<div class="study-step ${s.steps.lesson?'done':''}"><b>${s.steps.lesson?'✓':'3'}</b><div><strong>RSOS lesson</strong><span>${plan.task?`${plan.task.id} · ${plan.task.title_en}`:'Review week content'}</span></div></div>`:''}
 <div class="study-step ${s.steps.quiz?'done':''}"><b>${s.steps.quiz?'✓':'4'}</b><div><strong>Guided Red Seal questions</strong><span>${s.p.quizAnswered}/${s.r.quiz} answered · ${s.p.quizAnswered?Math.round(s.p.quizCorrect/s.p.quizAnswered*100):0}% correct</span></div></div>
 </div>`}
function render(root,rsos,onChange){const profile=window.ProfileStore.active(),progress=window.ProgressStore.load(),today=currentDay(profile),now=planForDay(profile,progress,rsos,today),s=statusFor(today,now),next=nextStep(now,s),completed=new Set(progress.calendar.completedDays||[]);root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">180-DAY STUDY PLAN</p><h2>${escapeHtml(profile.name)} · Day ${today}/180</h2><p class="microcopy">Progress is saved automatically for this local user. A day closes only after its required study steps are completed.</p></div><div class="calendar-summary"><strong>${escapeHtml(profile.startDate)} → ${escapeHtml(profile.targetDate)}</strong><span>${completed.size}/180 study days completed</span></div></div>
 <article class="card today-workflow"><div class="today-workflow-head"><div><span class="badge">TODAY · ${escapeHtml(now.phase)}</span><h3>${escapeHtml(now.title)}</h3><p>${escapeHtml(now.desc)}</p></div><div class="day-status ${s.complete?'complete':'inprogress'}">${s.complete?'✓ DAY COMPLETE':'IN PROGRESS'}</div></div>${renderChecklist(now,s)}<button class="button primary" id="continue-today">${escapeHtml(next.label)}</button></article>
 <div class="calendar-legend"><span>Core study</span><span>Weekly review</span><span>Integration</span><span>Full mock</span></div><div class="six-month-grid">${Array.from({length:180},(_,x)=>{const d=x+1,pl=planForDay(profile,progress,rsos,d),done=completed.has(d),current=d===today;return `<button class="day-cell ${pl.kind} ${done?'done':''} ${current?'current':''}" data-day="${d}" title="Day ${d}: ${escapeHtml(pl.title)}"><b>${d}</b><small>${escapeHtml(dateFor(profile,d).slice(5))}</small></button>`}).join('')}</div><div id="calendar-detail"></div>`;
 root.querySelector('#continue-today').onclick=()=>go(next.tab,next.mode,now.task?.id||null);
 root.querySelectorAll('.day-cell').forEach(btn=>btn.onclick=()=>{const d=Number(btn.dataset.day),pl=planForDay(profile,window.ProgressStore.load(),rsos,d),st=statusFor(d,pl);root.querySelector('#calendar-detail').innerHTML=`<article class="card day-detail"><span class="badge">Day ${d} · ${escapeHtml(pl.phase)}</span><h3>${escapeHtml(pl.title)}</h3><p>${escapeHtml(pl.desc)}</p>${renderChecklist(pl,st)}${d===today?`<button class="button secondary" id="detail-continue">${escapeHtml(nextStep(pl,st).label)}</button>`:''}</article>`;const b=root.querySelector('#detail-continue');if(b){const n=nextStep(pl,st);b.onclick=()=>go(n.tab,n.mode,pl.task?.id||null)}})
}
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
window.StudyCalendar={render,currentDay,planForDay,requirementsForDay,statusFor,nextStep};
})();
