/* 180-day study calendar generated from the official Task blueprint and user weaknesses. */
(function(){
'use strict';
const DAY=86400000;
function daysBetween(a,b){return Math.floor((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/DAY)}
function flatten(rsos){return rsos.mwas.flatMap(m=>m.tasks.map(t=>({...t,mwa:m.id,mwaTitle:m.title_en}))) }
function weightedTasks(rsos){return flatten(rsos).flatMap(t=>Array(Math.max(1,t.exam_questions)).fill(t))}
function planForDay(profile,progress,rsos,day){const all=flatten(rsos),weighted=weightedTasks(rsos),i=Math.max(1,Math.min(180,day));if(i<=126){if(i%7===0)return{day:i,phase:'Build the RSOS foundation',kind:'weekly-review',title:'Weekly consolidation + timed mixed set',minutes:80,vocab:10,questions:25,desc:'Review this week’s Tasks, redo mistakes and complete a timed mixed set in English.'};const t=weighted[(i*7+Math.floor(i/7))%weighted.length];return{day:i,phase:'Build the RSOS foundation',kind:'core',title:`${t.id} · ${t.title_en}`,minutes:65,vocab:5,questions:12,task:t,desc:'Study the Task/Sub-tasks, technical English and source-grounded application questions.'}}if(i<=154){if(i%7===0)return{day:i,phase:'Integration & troubleshooting',kind:'mixed-test',title:'Timed 50-question mixed test',minutes:130,vocab:10,questions:50,desc:'Work in English. Review errors at Task/Sub-task level after the test.'};const t=weighted[(i*11)%weighted.length];return{day:i,phase:'Integration & troubleshooting',kind:'integration',title:`Applied diagnosis · ${t.id}`,minutes:80,vocab:8,questions:18,task:t,desc:'Prioritize procedural and critical-thinking scenarios. Explain why each distractor is wrong.'}}if([160,167,174,178,180].includes(i))return{day:i,phase:'Final exam readiness',kind:'full-mock',title:'100-question / 4-hour full mock',minutes:240,vocab:0,questions:100,desc:'English-only exam simulation using the official Task blueprint. Review errors only after finishing.'};const weak=window.ProgressStore.weakTasks(10);const wid=weak[(i-155)%Math.max(1,weak.length)]?.task;const t=all.find(x=>x.id===wid)||weighted[(i*5)%weighted.length];return{day:i,phase:'Final exam readiness',kind:'remediation',title:`Weak-area remediation · ${t.id}`,minutes:90,vocab:12,questions:20,task:t,desc:'Repair weak areas, review formulas/acronyms and repeat missed concepts.'}}
function currentDay(profile){return Math.max(1,Math.min(180,daysBetween(profile.startDate,window.ProfileStore.today())+1))}
function dateFor(profile,day){return window.ProfileStore.addDays(profile.startDate,day-1)}
function render(root,rsos,onChange){const profile=window.ProfileStore.active(),p=window.ProgressStore.load(),today=currentDay(profile),now=planForDay(profile,p,rsos,today);const completed=new Set(p.calendar.completedDays);root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">180-DAY STUDY PLAN</p><h2>Your six-month Red Seal calendar</h2></div><div class="calendar-summary"><strong>Day ${today}/180</strong><span>${escapeHtml(profile.startDate)} → ${escapeHtml(profile.targetDate)}</span></div></div><article class="card today-plan"><div><span class="badge">${escapeHtml(now.phase)}</span><h3>${escapeHtml(now.title)}</h3><p>${escapeHtml(now.desc)}</p><div class="plan-metrics"><span>⏱ ${now.minutes} min</span><span>🔤 ${now.vocab} vocab</span><span>📝 ${now.questions} questions</span></div></div><button class="button ${completed.has(today)?'success':'primary'}" id="toggle-today">${completed.has(today)?'✓ Completed':'Mark today complete'}</button></article><div class="calendar-legend"><span>Core study</span><span>Weekly review</span><span>Integration</span><span>Full mock</span></div><div class="six-month-grid">${Array.from({length:180},(_,x)=>{const d=x+1,pl=planForDay(profile,p,rsos,d),done=completed.has(d),current=d===today;return `<button class="day-cell ${pl.kind} ${done?'done':''} ${current?'current':''}" data-day="${d}" title="Day ${d}: ${escapeHtml(pl.title)}"><b>${d}</b><small>${escapeHtml(dateFor(profile,d).slice(5))}</small></button>`}).join('')}</div><div id="calendar-detail"></div>`;root.querySelector('#toggle-today').addEventListener('click',()=>{window.ProgressStore.markDay(today,!completed.has(today));render(root,rsos,onChange);onChange?.()});root.querySelectorAll('.day-cell').forEach(btn=>btn.addEventListener('click',()=>{const d=Number(btn.dataset.day),pl=planForDay(profile,window.ProgressStore.load(),rsos,d);root.querySelector('#calendar-detail').innerHTML=`<article class="card day-detail"><span class="badge">Day ${d} · ${escapeHtml(pl.phase)}</span><h3>${escapeHtml(pl.title)}</h3><p>${escapeHtml(pl.desc)}</p><p><strong>${pl.minutes} min</strong> · ${pl.vocab} vocabulary · ${pl.questions} questions</p>${pl.task?`<p>${pl.task.subtasks.map(s=>`<span class="subtask-chip">${escapeHtml(s.id)} ${escapeHtml(s.title_en)}</span>`).join(' ')}</p>`:''}</article>`}))}
function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
window.StudyCalendar={render,currentDay,planForDay};
})();
