/* Technical English: Task-targeted vocabulary + spaced repetition + objective daily evaluation. */
(function(){
'use strict';
const DAY=86400000;
function initial(){return{repetitions:0,interval:0,easeFactor:2.5,due:Date.now(),reviews:0,lastQuality:null}}
function sm2(prev,quality){const s={...initial(),...(prev||{})};s.reviews++;s.lastQuality=quality;if(quality<3){s.repetitions=0;s.interval=1}else{s.repetitions++;if(s.repetitions===1)s.interval=1;else if(s.repetitions===2)s.interval=6;else s.interval=Math.max(1,Math.round(s.interval*s.easeFactor))}s.easeFactor=Math.max(1.3,s.easeFactor+(0.1-(5-quality)*(0.08+(5-quality)*0.02)));s.due=Date.now()+s.interval*DAY;return s}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
class EnglishController{
 constructor(root,terms,onProgress){this.root=root;this.terms=terms;this.onProgress=onProgress;this.index=0;this.mode='cards';this.render()}
 todayPlan(){const p=window.ProfileStore.active(),s=window.ProgressStore.load(),day=window.StudyCalendar.currentDay(p);return window.StudyCalendar.planForDay(p,s,window.__RSOS_DATA__,day)}
 dailyTerms(){const plan=this.todayPlan(),count=Number(window.ProgressStore.getSetting('englishNewPerDay',5)),taskId=plan.task?.id||null,day=window.StudyCalendar.currentDay(window.ProfileStore.active());const due=this.terms.filter(t=>{const s=window.ProgressStore.getVocab(t.id);return s&&s.due<=Date.now()});const taskPool=shuffle(this.terms.filter(t=>taskId&&t.task===taskId&&!window.ProgressStore.getVocab(t.id)));const examPool=shuffle(this.terms.filter(t=>!t.task&&!window.ProgressStore.getVocab(t.id)));const other=shuffle(this.terms.filter(t=>!window.ProgressStore.getVocab(t.id)));const fresh=[...taskPool,...examPool,...other].filter((t,i,a)=>a.findIndex(x=>x.id===t.id)===i).slice(0,count);const map=new Map([...due.slice(0,Math.max(10,count)),...fresh].map(t=>[t.id,t]));return[...map.values()]}
 render(){const stats=window.ProgressStore.stats(),plan=this.todayPlan(),day=window.StudyCalendar.currentDay(window.ProfileStore.active()),dp=window.ProgressStore.getDayProgress(day),req=window.StudyCalendar.requirementsForDay(plan);this.root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">TECHNICAL ENGLISH · CANADA · en-CA</p><h2>English for today’s Red Seal study</h2><p class="microcopy">${plan.task?`Priority vocabulary: ${esc(plan.task.id)} · ${esc(plan.task.title_en)}`:'Mixed exam-language review'}. Spanish help can be hidden at any time.</p></div><div class="mini-stats"><b>${stats.mastered}</b><span>mastered / ${this.terms.length}</span></div></div>
 <div class="english-status card"><div><strong>Today</strong><span>${new Set(dp.vocabReviewed||[]).size}/${req.vocab} reviews · evaluation ${dp.vocabTestPct==null?'pending':dp.vocabTestPct+'%'}</span></div><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,(new Set(dp.vocabReviewed||[]).size/Math.max(1,req.vocab))*100)}%"></div></div></div>
 <div class="english-tabs"><button class="button secondary" id="eng-cards">1 · Learn/review</button><button class="button primary" id="eng-test">2 · Daily evaluation · target 80%</button></div><div id="english-stage"></div>`;this.root.querySelector('#eng-cards').onclick=()=>this.open('cards');this.root.querySelector('#eng-test').onclick=()=>this.open('test');this.renderCard()}
 open(mode='cards'){this.mode=mode;this.index=0;if(mode==='test')this.startTest();else this.renderCard()}
 renderCard(){const list=this.dailyTerms(),stage=this.root.querySelector('#english-stage');if(!list.length){stage.innerHTML='<div class="empty-state">All scheduled vocabulary is complete. Take the daily evaluation.</div>';return}this.index%=list.length;const t=list[this.index],s=window.ProgressStore.getVocab(t.id)||initial();stage.innerHTML=`<article class="card vocab-card"><div class="badge-row"><span class="badge">${esc(t.category)}</span>${t.task?`<span class="badge muted">${esc(t.task)}</span>`:''}<span class="badge muted">${s.reviews?'Review':'New'}</span></div><div class="term-line"><div><h3>${esc(t.term_en)}</h3>${t.pronunciation?`<p class="pronunciation">${esc(t.pronunciation)}</p>`:''}</div><button class="icon-button" id="speak-vocab" aria-label="Hear pronunciation">🔊</button></div><p class="definition-en">${esc(t.definition_en)}</p><div class="lang-es spanish-panel"><strong>${esc(t.term_es)}</strong><p>${esc(t.definition_es)}</p></div><div class="example-box"><p lang="en">${esc(t.example_en)}</p><button class="text-button" id="speak-example">🔊 Hear example in Canadian English</button></div><p class="microcopy"><strong>Spaced repetition only:</strong> these buttons schedule when the term returns. Your real daily score comes from the objective evaluation.</p><div class="review-actions"><button class="button danger" data-q="1">Repeat</button><button class="button secondary" data-q="3">Difficult</button><button class="button success" data-q="5">Learned</button></div></article>`;stage.querySelector('#speak-vocab').onclick=()=>window.SpeechTools.speak(t.term_en);stage.querySelector('#speak-example').onclick=()=>window.SpeechTools.speak(t.example_en);stage.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{window.ProgressStore.updateVocab(t.id,sm2(s,Number(b.dataset.q)));this.index++;this.render();this.onProgress?.()})}
 startTest(){const dp=window.ProgressStore.getDayProgress(),studied=(dp.vocabReviewed||[]).map(id=>this.terms.find(t=>t.id===id)).filter(Boolean),fallback=this.dailyTerms(),list=shuffle((studied.length>=4?studied:fallback)).slice(0,Math.min(10,Math.max(4,studied.length||fallback.length)));const stage=this.root.querySelector('#english-stage');if(list.length<2){stage.innerHTML='<div class="empty-state">Study at least two vocabulary items before the evaluation.</div>';return}let i=0,score=0;const ask=()=>{if(i>=list.length){window.ProgressStore.recordVocabTest(score,list.length,list.map(t=>t.id));const pct=Math.round(score/list.length*100);stage.innerHTML=`<article class="card results-card"><p class="eyebrow">DAILY VOCABULARY EVALUATION</p><h2>${score}/${list.length}</h2><div class="score-ring">${pct}%</div><div class="pass-banner ${pct>=80?'pass':'fail'}">${pct>=80?'TARGET MET · ≥80%':'TARGET NOT MET · REVIEW AND RETRY'}</div><button class="button primary" id="back-vocab">${pct>=80?'Continue today’s plan':'Review words'}</button></article>`;stage.querySelector('#back-vocab').onclick=()=>window.dispatchEvent(new CustomEvent('study:navigate',{detail:{tab:pct>=80?'calendar':'english',mode:pct>=80?null:'cards'}}));this.onProgress?.();return}
 const t=list[i],others=shuffle(this.terms.filter(x=>x.id!==t.id&&x.category===t.category));const pool=others.length>=3?others:shuffle(this.terms.filter(x=>x.id!==t.id));const opts=shuffle([t,...pool.slice(0,3)]);stage.innerHTML=`<article class="card question-card"><span class="badge">Vocabulary evaluation ${i+1}/${list.length}</span><h3>Which technical term best matches this definition?</h3><p class="definition-prompt">${esc(t.definition_en)}</p><div class="options">${opts.map((o,n)=>`<button class="option" data-id="${o.id}"><b>${String.fromCharCode(65+n)}.</b> ${esc(o.term_en)}</button>`).join('')}</div><div id="vocab-feedback"></div></article>`;stage.querySelectorAll('.option').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.id)===t.id;if(ok)score++;stage.querySelectorAll('.option').forEach(x=>{x.disabled=true;if(Number(x.dataset.id)===t.id)x.classList.add('correct');else if(x===b&&!ok)x.classList.add('incorrect')});stage.querySelector('#vocab-feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><strong>${ok?'Correct':'Review'}</strong><p>${esc(t.term_en)} — ${esc(t.definition_en)}</p><p class="lang-es">${esc(t.term_es)} — ${esc(t.definition_es)}</p><button class="button primary" id="next-vocab-test">Next</button></div>`;stage.querySelector('#next-vocab-test').onclick=()=>{i++;ask()}})};ask()}
}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
window.EnglishController=EnglishController;
})();
