/* Red Seal Industrial Electrician practice engine: guided daily study, focused practice and 100-question mock. */
(function(){
'use strict';
class QuizController{
 constructor(root,questions,rsos,sources,onProgress){this.root=root;this.questions=questions;this.rsos=rsos;this.sources=sources;this.onProgress=onProgress;this.timer=null;this.session=[];this.answers=[];this.index=0;this.mode='practice';this.seconds=0;this.endAt=null;this.renderSetup()}
 shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
 taskList(){return this.rsos.mwas.flatMap(m=>m.tasks.map(t=>({...t,mwa:m.id})))}
 examLike(){return this.questions.filter(q=>q.verified!==false&&q.depth!=='scope')}
 buildBlueprint(){const TYPES=['Knowledge and Recall','Procedural and Application','Critical Thinking'],target=this.rsos.mock_exam_cognitive_mix?.simulation_counts||{'Knowledge and Recall':19,'Procedural and Application':38,'Critical Thinking':43},tasks=this.taskList().filter(t=>Number(t.exam_questions)>0),poolAll=this.examLike(),pools={};
   for(const t of tasks){pools[t.id]={};for(const type of TYPES)pools[t.id][type]=poolAll.filter(q=>q.task===t.id&&q.question_type===type)}
   let states=new Map([['0,0',[]]]);for(const t of tasks){const need=Number(t.exam_questions),opts=[];for(let k=0;k<=need;k++)for(let p=0;p<=need-k;p++){const c=need-k-p;if(k<=pools[t.id][TYPES[0]].length&&p<=pools[t.id][TYPES[1]].length&&c<=pools[t.id][TYPES[2]].length)opts.push([k,p,c])}if(!opts.length)throw new Error(`The exam-like bank needs more questions for ${t.id}.`);const next=new Map();for(const [key,plan] of states){const [sk,sp]=key.split(',').map(Number);for(const o of opts){const nk=sk+o[0],np=sp+o[1];if(nk>target[TYPES[0]]||np>target[TYPES[1]])continue;const key2=`${nk},${np}`;if(!next.has(key2))next.set(key2,[...plan,[t.id,o]])}}states=next}
   const plan=states.get(`${target[TYPES[0]]},${target[TYPES[1]]}`);if(!plan)throw new Error('Unable to build the 100-question simulation with the configured Red Seal mix.');const out=[];for(const [task,counts] of plan)for(let i=0;i<TYPES.length;i++)out.push(...this.shuffle(pools[task][TYPES[i]]).slice(0,counts[i]));if(out.length!==100)throw new Error(`Mock produced ${out.length} questions instead of 100.`);return this.shuffle(out)}
 todayContext(){const profile=window.ProfileStore.active(),progress=window.ProgressStore.load(),day=window.StudyCalendar.currentDay(profile),plan=window.StudyCalendar.planForDay(profile,progress,this.rsos,day),req=window.StudyCalendar.requirementsForDay(plan),dp=window.ProgressStore.getDayProgress(day);return{day,plan,req,dp}}
 buildGuided(){const {plan,req,dp}=this.todayContext(),all=this.examLike(),need=Math.max(1,req.quiz-Number(dp.quizAnswered||0)),used=new Set(dp.quizQuestionIds||[]),missed=new Set(window.ProgressStore.missedQuestionIds(30)),weakTasks=new Set(window.ProgressStore.weakTasks(6).map(x=>x.task));let out=[];
   const focus=plan.task?.id?this.shuffle(all.filter(q=>q.task===plan.task.id&&!used.has(q.id))):[];const focusN=Math.min(focus.length,Math.ceil(need*.6));out.push(...focus.slice(0,focusN));
   const remedial=this.shuffle(all.filter(q=>!used.has(q.id)&&!out.some(x=>x.id===q.id)&&(missed.has(q.id)||weakTasks.has(q.task))));out.push(...remedial.slice(0,Math.ceil(need*.3)));
   const mixed=this.shuffle(all.filter(q=>!used.has(q.id)&&!out.some(x=>x.id===q.id)));out.push(...mixed.slice(0,need-out.length));
   if(out.length<need){const repeats=this.shuffle(all.filter(q=>!out.some(x=>x.id===q.id)));out.push(...repeats.slice(0,need-out.length))}return this.shuffle(out.slice(0,need))}
 filters(){const mwa=this.root.querySelector('#q-mwa')?.value||'ALL',task=this.root.querySelector('#q-task')?.value||'ALL',type=this.root.querySelector('#q-type')?.value||'ALL',style=this.root.querySelector('#q-style')?.value||'exam';return this.questions.filter(q=>(style==='map'?q.depth==='scope':q.depth!=='scope')&&q.verified!==false&&(mwa==='ALL'||q.mwa===mwa)&&(task==='ALL'||q.task===task)&&(type==='ALL'||q.question_type===type))}
 open(mode='guided'){if(mode==='exam'||mode==='guided'||mode==='practice'||mode==='map')this.start(mode);else this.renderSetup()}
 resumeSession(){const saved=window.ProgressStore.getQuizSession();if(!saved?.ids?.length)return;const map=new Map(this.questions.map(q=>[Number(q.id),q]));this.session=saved.ids.map(id=>map.get(Number(id))).filter(Boolean);if(!this.session.length){window.ProgressStore.clearQuizSession();this.renderSetup();return}this.mode=saved.mode||'guided';this.answers=[...(saved.answers||[])];this.index=Math.min(Number(saved.index)||0,this.session.length-1);this.endAt=saved.endAt||null;if(this.mode==='exam'){this.seconds=Math.max(0,Math.floor((Number(this.endAt)-Date.now())/1000));if(this.seconds<=0){this.finish(true);return}this.startTimer()}this.renderQuestion()}
 start(mode){this.mode=mode;this.index=0;this.answers=[];clearInterval(this.timer);try{if(mode==='exam'){this.session=this.buildBlueprint();this.seconds=240*60;this.startTimer()}else if(mode==='guided'){this.session=this.buildGuided()}else if(mode==='map'){this.session=this.shuffle(this.questions.filter(q=>q.depth==='scope')).slice(0,20)}else{this.session=this.shuffle(this.filters()).slice(0,Math.min(30,this.filters().length))}}catch(e){alert(e.message);return}if(!this.session.length){alert(mode==='guided'?'Today’s guided requirement is already complete.':'No questions match this selection.');this.renderSetup();return}this.endAt=mode==='exam'?Date.now()+240*60*1000:null;window.ProgressStore.saveQuizSession({mode:this.mode,ids:this.session.map(q=>q.id),answers:this.answers,index:this.index,endAt:this.endAt});window.ProgressStore.setResume('quiz',mode,this.session[0]?.id);this.renderQuestion()}
 startTimer(){clearInterval(this.timer);this.timer=setInterval(()=>{this.seconds=this.endAt?Math.max(0,Math.floor((this.endAt-Date.now())/1000)):Math.max(0,this.seconds-1);const x=this.root.querySelector('#quiz-timer');if(x)x.textContent=this.fmt(this.seconds);window.ProgressStore.saveQuizSession({mode:this.mode,ids:this.session.map(q=>q.id),answers:this.answers,index:this.index,endAt:this.endAt});if(this.seconds<=0){clearInterval(this.timer);this.finish(true)}},1000)}
 fmt(s){s=Math.max(0,s);return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
 renderSetup(){const tasks=this.taskList(),types=['Knowledge and Recall','Procedural and Application','Critical Thinking'],ctx=this.todayContext(),remaining=Math.max(0,ctx.req.quiz-Number(ctx.dp.quizAnswered||0)),saved=window.ProgressStore.getQuizSession();this.root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">RED SEAL INDUSTRIAL ELECTRICIAN</p><h2>Exam-style practice</h2><p class="microcopy">Default practice excludes RSOS-map classification drills and prioritizes application, calculation, procedural and critical-thinking questions.</p></div><div class="source-status"><span class="verified-dot"></span>${this.examLike().length} exam-style/source-grounded questions</div></div>
 ${saved?`<article class="card resume-banner"><div><span class="badge">SAVED SESSION</span><h3>Resume ${esc(saved.mode||'study')} session</h3><p>Question ${(saved.index||0)+1} of ${saved.ids?.length||0}. Your answers are saved for this user.</p></div><button class="button primary" id="resume-session">Resume</button></article>`:''}<article class="card guided-banner"><div><span class="badge">TODAY · DAY ${ctx.day}</span><h3>${ctx.plan.task?`${ctx.plan.task.id} · ${esc(ctx.plan.task.title_en)}`:esc(ctx.plan.title)}</h3><p>${remaining?`${remaining} guided questions remain today. Focus is today’s Task plus missed/weak areas.`:'Today’s guided-question requirement is complete.'}</p></div><button class="button primary" id="start-guided" ${remaining?'':'disabled'}>${remaining?'Continue today’s guided study':'Completed'}</button></article>
 <div class="quiz-filter-grid"><label class="field">MWA<select id="q-mwa"><option value="ALL">All MWAs</option>${this.rsos.mwas.map(m=>`<option value="${m.id}">${m.id} · ${esc(m.title_en)}</option>`).join('')}</select></label><label class="field">Task<select id="q-task"><option value="ALL">All Tasks</option>${tasks.map(t=>`<option value="${t.id}">${t.id} · ${esc(t.title_en)}</option>`).join('')}</select></label><label class="field">Question type<select id="q-type"><option value="ALL">All types</option>${types.map(t=>`<option>${t}</option>`).join('')}</select></label><label class="field">Study style<select id="q-style"><option value="exam">Exam-like / technical</option><option value="map">RSOS map drill only</option></select></label></div>
 <div class="quiz-launch-grid three"><button class="mode-card" id="start-practice"><span class="mode-icon">🧠</span><strong>Focused practice</strong><span>Up to 30 exam-like questions using your filters.</span></button><button class="mode-card" id="start-map"><span class="mode-icon">🗺️</span><strong>RSOS map drill</strong><span>Optional Task/Sub-task classification review. Kept separate from exam-style practice.</span></button><button class="mode-card exam-card" id="start-exam"><span class="mode-icon">⏱️</span><strong>100-question mock</strong><span>4 hours · official Task counts · English only · 70% pass mark.</span></button></div>
 <article class="card blueprint-card"><h3>Official exam blueprint</h3><div class="weight-grid">${this.rsos.mwas.map(m=>`<div><b>${m.id}</b><span>${m.weight}%</span><small>${m.title_en}</small></div>`).join('')}</div><p class="microcopy">The Red Seal publishes Task question counts and cognitive-type ranges. This simulator uses 19 Knowledge/Recall, 38 Procedural/Application and 43 Critical Thinking within those published global ranges; that exact 19/38/43 split is our simulation, not an official fixed exam composition.</p></article>`;
 const resumeBtn=this.root.querySelector('#resume-session');if(resumeBtn)resumeBtn.onclick=()=>this.resumeSession();this.root.querySelector('#q-mwa').onchange=e=>{const m=e.target.value,sel=this.root.querySelector('#q-task');[...sel.options].forEach(o=>{if(o.value==='ALL')return;o.hidden=m!=='ALL'&&!o.value.startsWith(m+'-')});sel.value='ALL'};this.root.querySelector('#start-guided').onclick=()=>this.start('guided');this.root.querySelector('#start-practice').onclick=()=>this.start('practice');this.root.querySelector('#start-map').onclick=()=>this.start('map');this.root.querySelector('#start-exam').onclick=()=>this.start('exam')}
 renderQuestion(){if(this.index>=this.session.length){this.finish(false);return}const q=this.session[this.index],answer=this.answers[this.index],exam=this.mode==='exam';window.ProgressStore.saveQuizSession({mode:this.mode,ids:this.session.map(x=>x.id),answers:this.answers,index:this.index,endAt:this.endAt});document.body.classList.toggle('exam-english-only',exam);window.ProgressStore.setResume('quiz',this.mode,q.id);this.root.innerHTML=`<div class="quiz-topbar"><button class="text-button" id="exit-quiz">← Exit</button><div class="quiz-progress"><span>${this.index+1}/${this.session.length}</span><div class="progress-track"><div class="progress-fill" style="width:${(this.index+1)/this.session.length*100}%"></div></div></div>${exam?`<span class="timer" id="quiz-timer">${this.fmt(this.seconds)}</span>`:'<span></span>'}</div>
 <article class="card question-card"><div class="badge-row"><span class="badge">MWA ${q.mwa}</span><span class="badge muted">${esc(q.task)}</span>${q.subtask?`<span class="badge muted">${esc(q.subtask)}</span>`:''}<span class="badge muted">${esc(q.question_type)}</span>${q.depth==='scope'?'<span class="badge muted">RSOS MAP</span>':'<span class="badge verified">✓ exam-style study</span>'}</div><div class="question-title-row"><h3 lang="en">${esc(q.question_en)}</h3><button class="icon-button" id="speak-question">🔊</button></div><div class="options">${q.options.map((o,i)=>`<button class="option ${answer===i?'selected':''}" data-i="${i}"><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</button>`).join('')}</div><div id="answer-feedback"></div>${exam?`<div class="exam-nav"><button class="button secondary" id="prev-q" ${this.index===0?'disabled':''}>Previous</button><button class="button primary" id="next-q">${this.index===this.session.length-1?'Finish exam':'Next'}</button></div>`:''}</article>`;
 this.root.querySelector('#exit-quiz').onclick=()=>{clearInterval(this.timer);window.ProgressStore.saveQuizSession({mode:this.mode,ids:this.session.map(x=>x.id),answers:this.answers,index:this.index,endAt:this.endAt});document.body.classList.remove('exam-english-only');this.renderSetup()};this.root.querySelector('#speak-question').onclick=()=>window.SpeechTools.speak(q.question_en);this.root.querySelectorAll('.option').forEach(b=>b.onclick=()=>this.choose(Number(b.dataset.i)));if(exam){this.root.querySelector('#prev-q').onclick=()=>{this.index--;this.renderQuestion()};this.root.querySelector('#next-q').onclick=()=>{if(this.index===this.session.length-1)this.finish(false);else{this.index++;this.renderQuestion()}}}}
 choose(i){const q=this.session[this.index],exam=this.mode==='exam';this.answers[this.index]=i;window.ProgressStore.saveQuizSession({mode:this.mode,ids:this.session.map(x=>x.id),answers:this.answers,index:this.index,endAt:this.endAt});if(exam){this.renderQuestion();return}const ok=i===q.correct;window.ProgressStore.recordQuizAnswer(q,ok,{selectedIndex:i,mode:this.mode});this.onProgress?.();this.root.querySelectorAll('.option').forEach(b=>{b.disabled=true;const n=Number(b.dataset.i);if(n===q.correct)b.classList.add('correct');if(n===i&&!ok)b.classList.add('incorrect')});const src=this.sources[q.source_id]||{};this.root.querySelector('#answer-feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><h4>${ok?'✓ Correct':'✕ Incorrect'}</h4><p>${esc(q.explanation_en)}</p><div class="lang-es"><strong>ES</strong><p>${esc(q.explanation_es)}</p></div><div class="evidence-box"><b>Source anchor</b><span>${esc(q.source_locator||'Official Red Seal source')}</span>${src.url?`<a href="${src.url}" target="_blank" rel="noopener">Open official source ↗</a>`:''}</div><button class="button primary" id="next-practice">Next</button></div>`;this.root.querySelector('#next-practice').onclick=()=>{this.index++;this.renderQuestion()}}
 finish(timeExpired){clearInterval(this.timer);window.ProgressStore.clearQuizSession();document.body.classList.remove('exam-english-only');if(this.mode!=='exam'){const answered=this.answers.filter(x=>x!==undefined).length,correct=this.answers.reduce((n,a,i)=>n+(a===this.session[i]?.correct?1:0),0),pct=answered?Math.round(correct/answered*100):0;window.ProgressStore.setResume('calendar',null,null);this.root.innerHTML=`<article class="card results-card"><p class="eyebrow">SESSION COMPLETE</p><h2>${correct}/${answered}</h2><div class="score-ring">${pct}%</div><p>${this.mode==='guided'?'Your result has been stored by Task, Sub-task and question. Incorrect questions are prioritized for future remediation.':'This result has been added to your personal progress.'}</p><button class="button primary" id="back-plan">Continue study plan</button><button class="button secondary" id="back-quiz">More practice</button></article>`;this.root.querySelector('#back-plan').onclick=()=>window.dispatchEvent(new CustomEvent('study:navigate',{detail:{tab:'calendar'}}));this.root.querySelector('#back-quiz').onclick=()=>this.renderSetup();this.onProgress?.();return}
 let correct=0;const byMwa={},byTask={};this.session.forEach((q,i)=>{const ok=this.answers[i]===q.correct;if(ok)correct++;byMwa[q.mwa]||={a:0,c:0};byMwa[q.mwa].a++;if(ok)byMwa[q.mwa].c++;byTask[q.task]||={a:0,c:0};byTask[q.task].a++;if(ok)byTask[q.task].c++;window.ProgressStore.recordQuizAnswer(q,ok,{selectedIndex:this.answers[i]??null,mode:'exam'})});const pct=Math.round(correct/this.session.length*100),passed=pct>=70;window.ProgressStore.recordExamAttempt({score:correct,total:this.session.length,pct,passed,timeExpired,byMwa,byTask});window.ProgressStore.setResume('progress',null,null);this.onProgress?.();this.root.innerHTML=`<article class="card exam-results"><p class="eyebrow">${timeExpired?'TIME EXPIRED':'MOCK EXAM COMPLETE'}</p><h2>${correct}/100 · ${pct}%</h2><div class="pass-banner ${passed?'pass':'fail'}">${passed?'PASS ≥ 70%':'BELOW 70%'}</div><div class="result-grid">${Object.entries(byMwa).map(([m,v])=>`<div><b>MWA ${m}</b><span>${Math.round(v.c/v.a*100)}%</span><small>${v.c}/${v.a}</small></div>`).join('')}</div><p>Weak Tasks and missed questions have been added to your remediation queue.</p><button class="button primary" id="return-plan">Continue study plan</button></article>`;this.root.querySelector('#return-plan').onclick=()=>window.dispatchEvent(new CustomEvent('study:navigate',{detail:{tab:'calendar'}}))}
}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
window.QuizController=QuizController;
})();
