/* Practice + 100-question / 4-hour Red Seal blueprint simulation. */
(function(){
'use strict';
class QuizController{
 constructor(root,questions,rsos,sources,onProgress){this.root=root;this.questions=questions;this.rsos=rsos;this.sources=sources;this.onProgress=onProgress;this.timer=null;this.session=[];this.answers=[];this.index=0;this.mode='practice';this.seconds=0;this.renderSetup()}
 shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
 taskList(){return this.rsos.mwas.flatMap(m=>m.tasks.map(t=>({...t,mwa:m.id})))}
 buildBlueprint(){
  const out=[],mix=this.rsos.mock_exam_cognitive_mix?.task_type_plan||{};
  for(const t of this.taskList()){
    const need=t.exam_questions;if(need===0)continue;
    const pool=this.questions.filter(q=>q.task===t.id&&q.verified!==false),plan=mix[t.id];
    if(plan){
      for(const [type,n] of Object.entries(plan)){
        const candidates=this.shuffle(pool.filter(q=>q.question_type===type));
        if(candidates.length<n)throw new Error(`Not enough source-grounded ${type} questions for ${t.id}`);
        out.push(...candidates.slice(0,n));
      }
    }else{
      const candidates=this.shuffle(pool);
      if(candidates.length<need)throw new Error(`Not enough source-grounded questions for ${t.id}`);
      out.push(...candidates.slice(0,need));
    }
  }
  if(out.length!==100)throw new Error(`Mock blueprint produced ${out.length} questions instead of 100`);
  return this.shuffle(out)
 }
 buildDaily(){
  const target={'Knowledge and Recall':2,'Procedural and Application':4,'Critical Thinking':4},out=[];
  for(const [type,n] of Object.entries(target))out.push(...this.shuffle(this.questions.filter(q=>q.verified!==false&&q.question_type===type)).slice(0,n));
  return this.shuffle(out)
 }
 filters(){const mwa=this.root.querySelector('#q-mwa')?.value||'ALL',task=this.root.querySelector('#q-task')?.value||'ALL',type=this.root.querySelector('#q-type')?.value||'ALL';return this.questions.filter(q=>(mwa==='ALL'||q.mwa===mwa)&&(task==='ALL'||q.task===task)&&(type==='ALL'||q.question_type===type))}
 start(mode){this.mode=mode;this.index=0;this.answers=[];clearInterval(this.timer);try{if(mode==='exam'){this.session=this.buildBlueprint();this.seconds=240*60;this.startTimer()}else if(mode==='daily'){this.session=this.buildDaily()}else{this.session=this.shuffle(this.filters()).slice(0,Math.min(30,this.filters().length))}}catch(e){alert(e.message);return}if(!this.session.length){alert('No verified questions match this filter.');return}this.renderQuestion()}
 startTimer(){this.timer=setInterval(()=>{this.seconds--;const x=this.root.querySelector('#quiz-timer');if(x)x.textContent=this.fmt(this.seconds);if(this.seconds<=0){clearInterval(this.timer);this.finish(true)}},1000)}
 fmt(s){s=Math.max(0,s);return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
 renderSetup(){const tasks=this.taskList(),types=['Knowledge and Recall','Procedural and Application','Critical Thinking'];this.root.innerHTML=`<div class="section-heading"><div><p class="eyebrow">RED SEAL INDUSTRIAL ELECTRICIAN</p><h2>Verified practice & exam simulation</h2></div><div class="source-status"><span class="verified-dot"></span>${this.questions.filter(q=>q.verified).length} source-grounded questions</div></div>
 <div class="quiz-filter-grid"><label class="field">MWA<select id="q-mwa"><option value="ALL">All MWAs</option>${this.rsos.mwas.map(m=>`<option value="${m.id}">${m.id} · ${esc(m.title_en)}</option>`).join('')}</select></label><label class="field">Task<select id="q-task"><option value="ALL">All Tasks</option>${tasks.map(t=>`<option value="${t.id}">${t.id} · ${esc(t.title_en)}</option>`).join('')}</select></label><label class="field">Question type<select id="q-type"><option value="ALL">All types</option>${types.map(t=>`<option>${t}</option>`).join('')}</select></label></div>
 <div class="quiz-launch-grid three"><button class="mode-card" id="start-daily"><span class="mode-icon">🎯</span><strong>Daily 10</strong><span>Short mixed session with explanations and sources.</span></button><button class="mode-card" id="start-practice"><span class="mode-icon">🧠</span><strong>Focused practice</strong><span>Up to 30 questions using the selected filters.</span></button><button class="mode-card exam-card" id="start-exam"><span class="mode-icon">⏱️</span><strong>100-question mock</strong><span>4 hours · official Task counts · cognitive mix within official ranges · English only · 70% pass mark.</span></button></div>
 <article class="card blueprint-card"><h3>Official exam blueprint</h3><div class="weight-grid">${this.rsos.mwas.map(m=>`<div><b>${m.id}</b><span>${m.weight}%</span><small>${m.title_en}</small></div>`).join('')}</div><p class="microcopy">Practice questions are original study questions grounded in official Red Seal sources—not leaked or official exam questions. Mock cognitive mix: 19 Knowledge/Recall, 38 Procedural/Application, 43 Critical Thinking; this is a simulation allocation within the official published ranges, not an official fixed per-exam count.</p></article>`;
 this.root.querySelector('#q-mwa').onchange=e=>{const m=e.target.value,sel=this.root.querySelector('#q-task');[...sel.options].forEach(o=>{if(o.value==='ALL')return;o.hidden=m!=='ALL'&&!o.value.startsWith(m+'-')});sel.value='ALL'};this.root.querySelector('#start-daily').onclick=()=>this.start('daily');this.root.querySelector('#start-practice').onclick=()=>this.start('practice');this.root.querySelector('#start-exam').onclick=()=>this.start('exam')}
 renderQuestion(){if(this.index>=this.session.length){this.finish(false);return}const q=this.session[this.index],answer=this.answers[this.index];const exam=this.mode==='exam';document.body.classList.toggle('exam-english-only',exam);this.root.innerHTML=`<div class="quiz-topbar"><button class="text-button" id="exit-quiz">← Exit</button><div class="quiz-progress"><span>${this.index+1}/${this.session.length}</span><div class="progress-track"><div class="progress-fill" style="width:${(this.index+1)/this.session.length*100}%"></div></div></div>${exam?`<span class="timer" id="quiz-timer">${this.fmt(this.seconds)}</span>`:'<span></span>'}</div>
 <article class="card question-card"><div class="badge-row"><span class="badge">MWA ${q.mwa}</span><span class="badge muted">${esc(q.task)}</span>${q.subtask?`<span class="badge muted">${esc(q.subtask)}</span>`:''}<span class="badge muted">${esc(q.question_type)}</span><span class="badge verified">✓ source-grounded</span></div><div class="question-title-row"><h3 lang="en">${esc(q.question_en)}</h3><button class="icon-button" id="speak-question">🔊</button></div><div class="options">${q.options.map((o,i)=>`<button class="option ${answer===i?'selected':''}" data-i="${i}">${esc(o)}</button>`).join('')}</div><div id="answer-feedback"></div>${exam?`<div class="exam-nav"><button class="button secondary" id="prev-q" ${this.index===0?'disabled':''}>Previous</button><button class="button primary" id="next-q">${this.index===this.session.length-1?'Finish exam':'Next'}</button></div>`:''}</article>`;
 this.root.querySelector('#exit-quiz').onclick=()=>{clearInterval(this.timer);document.body.classList.remove('exam-english-only');this.renderSetup()};this.root.querySelector('#speak-question').onclick=()=>window.SpeechTools.speak(q.question_en);this.root.querySelectorAll('.option').forEach(b=>b.onclick=()=>this.choose(Number(b.dataset.i)));
 if(exam){this.root.querySelector('#prev-q').onclick=()=>{this.index--;this.renderQuestion()};this.root.querySelector('#next-q').onclick=()=>{if(this.index===this.session.length-1)this.finish(false);else{this.index++;this.renderQuestion()}}}
 }
 choose(i){const q=this.session[this.index],exam=this.mode==='exam';this.answers[this.index]=i;if(exam){this.renderQuestion();return}const ok=i===q.correct;window.ProgressStore.recordQuizAnswer(q,ok,{selectedIndex:i,mode:this.mode});this.onProgress?.();this.root.querySelectorAll('.option').forEach(b=>{b.disabled=true;const n=Number(b.dataset.i);if(n===q.correct)b.classList.add('correct');if(n===i&&!ok)b.classList.add('incorrect')});const src=this.sources[q.source_id]||{};this.root.querySelector('#answer-feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><h4>${ok?'✓ Correct':'✕ Incorrect'}</h4><p>${esc(q.explanation_en)}</p><div class="lang-es"><strong>ES</strong><p>${esc(q.explanation_es)}</p></div><div class="evidence-box"><b>Verification</b><span>${esc(q.source_locator||'Official source')}</span>${src.url?`<a href="${src.url}" target="_blank" rel="noopener">Open official Red Seal source ↗</a>`:''}</div><button class="button primary" id="next-practice">Next</button></div>`;this.root.querySelector('#next-practice').onclick=()=>{this.index++;this.renderQuestion()}}
 finish(timeExpired){clearInterval(this.timer);document.body.classList.remove('exam-english-only');if(this.mode!=='exam'){const answered=this.answers.filter(x=>x!==undefined).length;const correct=this.answers.reduce((n,a,i)=>n+(a===this.session[i]?.correct?1:0),0);this.showSimpleResult(correct,answered,timeExpired);return}let correct=0;const byMwa={};const byTask={};this.session.forEach((q,i)=>{const ok=this.answers[i]===q.correct;if(ok)correct++;byMwa[q.mwa]||={a:0,c:0};byMwa[q.mwa].a++;if(ok)byMwa[q.mwa].c++;byTask[q.task]||={a:0,c:0};byTask[q.task].a++;if(ok)byTask[q.task].c++;window.ProgressStore.recordQuizAnswer(q,ok,{selectedIndex:this.answers[i]??null,mode:'exam'})});const pct=Math.round(correct/this.session.length*100),passed=pct>=70;window.ProgressStore.recordExamAttempt({score:correct,total:this.session.length,pct,passed,timeExpired,byMwa,byTask});this.onProgress?.();this.root.innerHTML=`<article class="card exam-results"><p class="eyebrow">${timeExpired?'TIME EXPIRED':'MOCK EXAM COMPLETE'}</p><h2>${correct}/100 · ${pct}%</h2><div class="pass-banner ${passed?'pass':'fail'}">${passed?'PASS ≥ 70%':'BELOW 70% TARGET'}</div><div class="result-grid">${Object.entries(byMwa).map(([m,v])=>`<div><b>MWA ${m}</b><span>${Math.round(v.c/v.a*100)}%</span><small>${v.c}/${v.a}</small></div>`).join('')}</div><p>This is a study simulation. Actual certification eligibility and examination administration are handled by the provincial/territorial apprenticeship authority.</p><button class="button primary" id="return-quiz">Return to quiz</button></article>`;this.root.querySelector('#return-quiz').onclick=()=>this.renderSetup()}
 showSimpleResult(correct,answered,timeExpired){const pct=answered?Math.round(correct/answered*100):0;this.root.innerHTML=`<article class="card results-card"><p class="eyebrow">${timeExpired?'TIME EXPIRED':'SESSION COMPLETE'}</p><h2>${correct}/${answered}</h2><div class="score-ring">${pct}%</div><button class="button primary" id="back-quiz">Back to quiz</button></article>`;this.root.querySelector('#back-quiz').onclick=()=>this.renderSetup()}
}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
window.QuizController=QuizController;
})();
