/* UX layer: makes the Red Seal study sequence and quiz modes explicit without changing the study data. */
(function(){
'use strict';
function navigate(tab,mode){window.dispatchEvent(new CustomEvent('study:navigate',{detail:{tab,mode}}));}
function enhanceDashboard(){const card=document.querySelector('.workflow-card');if(!card||card.dataset.uxEnhanced==='1')return;card.dataset.uxEnhanced='1';const checklist=card.querySelector('.study-checklist');if(!checklist)return;const intro=document.createElement('div');intro.className='ux-start-here';intro.innerHTML='<strong>START HERE</strong><span>Follow these steps in order. Each step opens the correct activity and your progress is saved automatically.</span>';checklist.parentNode.insertBefore(intro,checklist);const steps=[...checklist.querySelectorAll('.study-step')];const routes=steps.length===1?[{tab:'quiz',mode:'exam',label:'Open 100-question mock'}]:[{tab:'english',mode:'cards',label:'Study today’s words'},{tab:'english',mode:'test',label:'Take vocabulary test'},{tab:'rsos',mode:null,label:'Open today’s RSOS lesson'},{tab:'quiz',mode:'guided',label:'Answer today’s learning questions'}];steps.forEach((step,i)=>{const route=routes[i];if(!route)return;step.classList.add('ux-clickable-step');step.setAttribute('role','button');step.setAttribute('tabindex','0');const action=document.createElement('span');action.className='ux-step-action';action.textContent=step.classList.contains('done')?'Completed ✓':`${route.label} →`;step.appendChild(action);const go=()=>navigate(route.tab,route.mode);step.addEventListener('click',go);step.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}});});}
function sessionLabel(mode){if(mode==='exam')return 'FULL MOCK EXAM';if(mode==='guided')return 'TODAY’S LEARNING QUESTIONS';if(mode==='map')return 'OPTIONAL RSOS MAP DRILL';return 'PRACTICE BY TOPIC';}
function enhanceQuizSetup(ctrl){const root=ctrl.root;if(!root||root.querySelector('.ux-quiz-intro'))return;const heading=root.querySelector('.section-heading');if(heading){const intro=document.createElement('section');intro.className='ux-quiz-intro';intro.innerHTML='<div class="ux-quiz-title"><span>CHOOSE WHAT YOU WANT TO DO</span><h3>Questions are shown one at a time, in a visible sequence.</h3><p>Learning/practice tells you immediately if your answer is correct. The 100-question mock hides correctness until you submit the exam.</p></div><div class="ux-mode-key"><div><b>1</b><strong>Learn today</strong><span>Guided questions from today’s Task + weak areas.</span></div><div><b>2</b><strong>Practice</strong><span>Choose MWA/Task and receive instant correction.</span></div><div><b>3</b><strong>Mock exam</strong><span>100 questions, navigator 1–100, results at the end.</span></div></div>';heading.insertAdjacentElement('afterend',intro);}const guided=root.querySelector('#start-guided');if(guided&&!guided.disabled)guided.textContent='START TODAY’S LEARNING QUESTIONS';const practice=root.querySelector('#start-practice');if(practice){const strong=practice.querySelector('strong');if(strong)strong.textContent='Practice by topic';const text=practice.querySelector('span:last-child');if(text)text.textContent='Choose a Task above. Select A–D and see the correct answer immediately.';}const exam=root.querySelector('#start-exam');if(exam){const strong=exam.querySelector('strong');if(strong)strong.textContent='Full mock exam · 100 questions';const text=exam.querySelector('span:last-child');if(text)text.textContent='Your choices are saved. Correct answers stay hidden until you finish the exam.';}const map=root.querySelector('#start-map');if(map){map.classList.add('ux-advanced-mode');const strong=map.querySelector('strong');if(strong)strong.textContent='Optional RSOS map drill';}const filters=root.querySelector('.quiz-filter-grid');if(filters&&!filters.previousElementSibling?.classList.contains('ux-filter-title')){const p=document.createElement('div');p.className='ux-filter-title';p.innerHTML='<strong>Practice by topic filters</strong><span>These filters apply only to “Practice by topic”. You do not need them for today’s guided study or the mock exam.</span>';filters.parentNode.insertBefore(p,filters);}}
function buildNavigator(ctrl){const nav=document.createElement('div');nav.className=`ux-question-navigator ${ctrl.mode==='exam'?'exam-nav-grid':'study-nav-grid'}`;const title=document.createElement('div');title.className='ux-nav-title';title.innerHTML=`<strong>${sessionLabel(ctrl.mode)}</strong><span>${ctrl.session.length} questions total · you are on ${ctrl.index+1}</span>`;nav.appendChild(title);const grid=document.createElement('div');grid.className='ux-nav-grid';ctrl.session.forEach((q,i)=>{const el=document.createElement(ctrl.mode==='exam'?'button':'span');el.className='ux-nav-item';el.textContent=String(i+1);if(i===ctrl.index)el.classList.add('active');if(ctrl.answers[i]!==undefined)el.classList.add('answered');if(ctrl.mode==='exam'){el.type='button';el.title=`Go to question ${i+1}`;el.addEventListener('click',()=>{ctrl.index=i;ctrl.renderQuestion();});}grid.appendChild(el);});nav.appendChild(grid);return nav;}
function enhanceQuestion(ctrl){const root=ctrl.root,card=root?.querySelector('.question-card');if(!root||!card||root.querySelector('.ux-question-mode'))return;const top=root.querySelector('.quiz-topbar');if(top)top.insertAdjacentElement('afterend',buildNavigator(ctrl));const mode=document.createElement('div');mode.className='ux-question-mode';const answer=ctrl.answers[ctrl.index];if(ctrl.mode==='exam'){mode.innerHTML=`<strong>EXAM MODE</strong><span>${answer===undefined?'Select A, B, C or D.':'Answer '+String.fromCharCode(65+Number(answer))+' saved.'} The correct answer will not be shown until the exam ends.</span>`;}else{mode.innerHTML='<strong>LEARNING MODE</strong><span>Select A, B, C or D below. The app will immediately tell you if you are correct, explain why, and then show a <b>Next question</b> button.</span>';}const options=card.querySelector('.options');if(options){options.parentNode.insertBefore(mode,options);options.querySelectorAll('.option').forEach(btn=>{btn.type='button';btn.classList.add('ux-answer-button');});}if(ctrl.mode==='exam'){const examNav=card.querySelector('.exam-nav');if(examNav){const info=document.createElement('span');info.className='ux-exam-save-status';info.textContent=answer===undefined?'No answer selected yet':'Answer saved ✓';examNav.insertBefore(info,examNav.querySelector('#next-q'));}}}
function enhanceResults(ctrl){const root=ctrl.root;if(!root||root.querySelector('.ux-results-actions'))return;const result=root.querySelector('.results-card,.exam-results');if(!result)return;const actions=document.createElement('div');actions.className='ux-results-actions';actions.innerHTML='<button type="button" class="button secondary" data-ux-home>Back to Dashboard</button><button type="button" class="button primary" data-ux-quiz>More questions</button>';result.appendChild(actions);actions.querySelector('[data-ux-home]').onclick=()=>navigate('home');actions.querySelector('[data-ux-quiz]').onclick=()=>navigate('quiz');}
function patchQuiz(){const P=window.QuizController?.prototype;if(!P||P.__uxPatched)return;P.__uxPatched=true;const setup=P.renderSetup,question=P.renderQuestion,finish=P.finish;P.renderSetup=function(){const r=setup.apply(this,arguments);enhanceQuizSetup(this);return r;};P.renderQuestion=function(){const r=question.apply(this,arguments);enhanceQuestion(this);return r;};P.finish=function(){const r=finish.apply(this,arguments);enhanceResults(this);return r;};}
function renameQuizTab(){const b=document.querySelector('[data-tab="quiz"]');if(b)b.textContent='Questions & Exam';}
function observe(){const obs=new MutationObserver(()=>{enhanceDashboard();renameQuizTab();});obs.observe(document.documentElement,{subtree:true,childList:true});}
patchQuiz();document.addEventListener('DOMContentLoaded',()=>{renameQuizTab();enhanceDashboard();observe();});
})();
